mybatis:
  type-aliases-package: com.neo.entity

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root