//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 10:34:35 AM CST 
//


package com.data.data.hmly.service.elong.pojo;

import com.alibaba.fastjson.annotation.JSONField;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.util.List;


/**
 * <p>Java class for CreditCards complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="CreditCards">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CreditCardList" type="{}ArrayOfPaymentCardCategory" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditCards", propOrder = {
        "creditCardList"
})
public class CreditCards {

    @JSONField(name = "CreditCardList")
    protected List<PaymentCardCategory> creditCardList;

    /**
     * Gets the value of the creditCardList property.
     *
     * @return possible object is
     * {@link List < PaymentCardCategory > }
     */
    public List<PaymentCardCategory> getCreditCardList() {
        return creditCardList;
    }

    /**
     * Sets the value of the creditCardList property.
     *
     * @param value allowed object is
     *              {@link List < PaymentCardCategory > }
     */
    public void setCreditCardList(List<PaymentCardCategory> value) {
        this.creditCardList = value;
    }

}
