//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 10:34:35 AM CST 
//


package com.data.data.hmly.service.elong.pojo;

import com.alibaba.fastjson.annotation.JSONField;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HotelListCondition complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="HotelListCondition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ArrivalDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DepartureDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="CityId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QueryText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QueryType" type="{}EnumQueryType"/>
 *
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelListCondition", propOrder = {
        "arrivalDate",
        "departureDate",
        "cityId",
        "queryText",
        "queryType",

})
public class HotelIDListCondition {

    @JSONField(name = "ArrivalDate")
    @XmlSchemaType(name = "dateTime")
    protected java.util.Date arrivalDate;
    @JSONField(name = "DepartureDate")
    @XmlSchemaType(name = "dateTime")
    protected java.util.Date departureDate;
    @JSONField(name = "CityId")
    protected String cityId;
    @JSONField(name = "QueryText")
    protected String queryText;
    @JSONField(name = "QueryType")
    @XmlSchemaType(name = "string")
    protected EnumQueryType queryType;


    /**
     * Gets the value of the arrivalDate property.
     *
     * @return possible object is
     * {@link java.util.Date }
     */
    public java.util.Date getArrivalDate() {
        return arrivalDate;
    }

    /**
     * Sets the value of the arrivalDate property.
     * 大于等于昨天。当凌晨到店的搜索传入昨天的日期
     *
     * @param value allowed object is
     *              {@link java.util.Date }
     */
    public void setArrivalDate(java.util.Date value) {
        this.arrivalDate = value;
    }

    /**
     * Gets the value of the departureDate property.
     *
     * @return possible object is
     * {@link java.util.Date }
     */
    public java.util.Date getDepartureDate() {
        return departureDate;
    }

    /**
     * Sets the value of the departureDate property.
     * 至少晚于到店时间1天，不多于20天
     *
     * @param value allowed object is
     *              {@link java.util.Date }
     */
    public void setDepartureDate(java.util.Date value) {
        this.departureDate = value;
    }

    /**
     * Gets the value of the cityId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * Sets the value of the cityId property.
     * 使用位置查询时候可为空，其他查询需要传值
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCityId(String value) {
        this.cityId = value;
    }

    /**
     * Gets the value of the queryText property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getQueryText() {
        return queryText;
    }

    /**
     * Sets the value of the queryText property.
     * 全文检索，可以是酒店名、位置或品牌等。使用本参数的时候，需要输入CityId或DistictId
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setQueryText(String value) {
        this.queryText = value;
    }

    /**
     * Gets the value of the queryType property.
     *
     * @return possible object is
     * {@link EnumQueryType }
     */
    public EnumQueryType getQueryType() {
        return queryType;
    }

    /**
     * Sets the value of the queryType property.
     * Intelligent  智能搜索 （默认）HotelName  酒店名称 LocationName 位置名称
     *
     * @param value allowed object is
     *              {@link EnumQueryType }
     */
    public void setQueryType(EnumQueryType value) {
        this.queryType = value;
    }


}
