//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 10:34:35 AM CST 
//


package com.data.data.hmly.service.elong.pojo;

import com.alibaba.fastjson.annotation.JSONField;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HotelListCondition complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="HotelListCondition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ArrivalDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DepartureDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="CityId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QueryText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QueryType" type="{}EnumQueryType"/>
 *         &lt;element name="PaymentType" type="{}EnumPaymentType"/>
 *         &lt;element name="ProductProperties" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Facilities" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StarRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BrandId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GroupId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="LowRate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="HighRate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DistrictId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BusinessZoneId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LocationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Position" type="{}Position" minOccurs="0"/>
 *         &lt;element name="Sort" type="{}EnumSortType"/>
 *         &lt;element name="PageIndex" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PageSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CustomerType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ThemeIds" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CheckInPersonAmount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="BedTypes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResultType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HotelListCondition", propOrder = {
        "arrivalDate",
        "departureDate",
        "cityId",
        "queryText",
        "queryType",
        "paymentType",
        "productProperties",
        "facilities",
        "starRate",
        "brandId",
        "groupId",
        "lowRate",
        "highRate",
        "districtId",
        "businessZoneId",
        "locationId",
        "position",
        "sort",
        "pageIndex",
        "pageSize",
        "customerType",
        "themeIds",
        "checkInPersonAmount",
        "bedTypes",
        "resultType"
})
public class HotelListCondition {

    @JSONField(name = "ArrivalDate")
    @XmlSchemaType(name = "dateTime")
    protected java.util.Date arrivalDate;
    @JSONField(name = "DepartureDate")
    @XmlSchemaType(name = "dateTime")
    protected java.util.Date departureDate;
    @JSONField(name = "CityId")
    protected String cityId;
    @JSONField(name = "QueryText")
    protected String queryText;
    @JSONField(name = "QueryType")
    @XmlSchemaType(name = "string")
    protected EnumQueryType queryType;
    @JSONField(name = "PaymentType")
    @XmlSchemaType(name = "string")
    protected EnumPaymentType paymentType;
    @JSONField(name = "ProductProperties")
    protected String productProperties;
    @JSONField(name = "Facilities")
    protected String facilities;
    @JSONField(name = "StarRate")
    protected String starRate;
    @JSONField(name = "BrandId")
    protected String brandId;
    @JSONField(name = "GroupId")
    protected int groupId;
    @JSONField(name = "LowRate")
    protected int lowRate;
    @JSONField(name = "HighRate")
    protected int highRate;
    @JSONField(name = "DistrictId")
    protected String districtId;
    @JSONField(name = "BusinessZoneId")
    protected String businessZoneId;
    @JSONField(name = "LocationId")
    protected String locationId;
    @JSONField(name = "Position")
    protected Position position;
    @JSONField(name = "Sort")
    @XmlSchemaType(name = "string")
    protected EnumSortType sort;
    @JSONField(name = "PageIndex")
    protected int pageIndex;
    @JSONField(name = "PageSize")
    protected int pageSize;
    @JSONField(name = "CustomerType")
    protected String customerType;
    @JSONField(name = "ThemeIds")
    protected String themeIds;
    @JSONField(name = "CheckInPersonAmount")
    protected int checkInPersonAmount;
    @JSONField(name = "BedTypes")
    protected String bedTypes;
    @JSONField(name = "ResultType")
    protected String resultType;

    /**
     * Gets the value of the arrivalDate property.
     *
     * @return possible object is
     * {@link java.util.Date }
     */
    public java.util.Date getArrivalDate() {
        return arrivalDate;
    }

    /**
     * Sets the value of the arrivalDate property.
     * 大于等于昨天。当凌晨到店的搜索传入昨天的日期
     *
     * @param value allowed object is
     *              {@link java.util.Date }
     */
    public void setArrivalDate(java.util.Date value) {
        this.arrivalDate = value;
    }

    /**
     * Gets the value of the departureDate property.
     *
     * @return possible object is
     * {@link java.util.Date }
     */
    public java.util.Date getDepartureDate() {
        return departureDate;
    }

    /**
     * Sets the value of the departureDate property.
     * 至少晚于到店时间1天，不多于20天
     *
     * @param value allowed object is
     *              {@link java.util.Date }
     */
    public void setDepartureDate(java.util.Date value) {
        this.departureDate = value;
    }

    /**
     * Gets the value of the cityId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * Sets the value of the cityId property.
     * 使用位置查询时候可为空，其他查询需要传值
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCityId(String value) {
        this.cityId = value;
    }

    /**
     * Gets the value of the queryText property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getQueryText() {
        return queryText;
    }

    /**
     * Sets the value of the queryText property.
     * 全文检索，可以是酒店名、位置或品牌等。使用本参数的时候，需要输入CityId或DistictId
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setQueryText(String value) {
        this.queryText = value;
    }

    /**
     * Gets the value of the queryType property.
     *
     * @return possible object is
     * {@link EnumQueryType }
     */
    public EnumQueryType getQueryType() {
        return queryType;
    }

    /**
     * Sets the value of the queryType property.
     * Intelligent  智能搜索 （默认）HotelName  酒店名称 LocationName 位置名称
     *
     * @param value allowed object is
     *              {@link EnumQueryType }
     */
    public void setQueryType(EnumQueryType value) {
        this.queryType = value;
    }

    /**
     * Gets the value of the paymentType property.
     *
     * @return possible object is
     * {@link EnumPaymentType }
     */
    public EnumPaymentType getPaymentType() {
        return paymentType;
    }

    /**
     * Sets the value of the paymentType property.
     *
     * @param value allowed object is
     *              {@link EnumPaymentType }
     */
    public void setPaymentType(EnumPaymentType value) {
        this.paymentType = value;
    }

    /**
     * Gets the value of the productProperties property.
     * All-全部、SelfPay-现付、Prepay-预付
     *
     * @return possible object is
     * {@link String }
     */
    public String getProductProperties() {
        return productProperties;
    }

    /**
     * Sets the value of the productProperties property.
     * 2015.02.10修改类型为String，支持多个选项同时传入，以逗号分隔。本参数是筛选包含指定条件的酒店，结果中的酒店可能包含其他属性的产品请自行过滤。可选值为：
     * All =全部,
     * LastMinuteSale =今日特价,
     * LimitedTimeSale =限时抢购,
     * WithoutGuarantee =免担保
     * AdvanceBooking=早订省
     * LongStayBooking=连住省
     * HourlyRoom=钟点房
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProductProperties(String value) {
        this.productProperties = value;
    }

    /**
     * Gets the value of the facilities property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFacilities() {
        return facilities;
    }

    /**
     * Sets the value of the facilities property.
     * 可以逗号分隔的组合，建议最多3个。
     * 1        免费wifi
     * 2        收费wifi
     * 3        免费宽带
     * 4        收费宽带
     * 5        免费停车场
     * 6        收费停车场
     * 7        免费接机服务
     * 8        收费接机服务
     * 9        室内游泳池
     * 10      室外游泳池
     * 11      健身房
     * 12      商务中心
     * 13      会议室
     * 14      酒店餐厅
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFacilities(String value) {
        this.facilities = value;
    }

    /**
     * Gets the value of the starRate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStarRate() {
        return starRate;
    }

    /**
     * Sets the value of the starRate property.
     * 推荐星级
     * 对应xml中的Category。搜索多个星级以逗号分隔
     * 经济/客栈: 0,1,2
     * 三星/舒适: 3
     * 四星/高档: 4
     * 五星/豪华: 5
     * 公寓: A
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStarRate(String value) {
        this.starRate = value;
    }

    /**
     * Gets the value of the brandId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * Sets the value of the brandId property.
     * 品牌编码
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBrandId(String value) {
        this.brandId = value;
    }

    /**
     * Gets the value of the groupId property.
     */
    public int getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 酒店集团编码
     */
    public void setGroupId(int value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the lowRate property.
     */
    public int getLowRate() {
        return lowRate;
    }

    /**
     * Sets the value of the lowRate property.
     * 过滤的是酒店中的产品,如果酒店的产品有一个满足这个区间这个酒店就算满足这个条件。注意不是按酒店最低价格来过滤的。
     */
    public void setLowRate(int value) {
        this.lowRate = value;
    }

    /**
     * Gets the value of the highRate property.
     */
    public int getHighRate() {
        return highRate;
    }

    /**
     * Sets the value of the highRate property.
     * 过滤的是酒店中的产品,如果酒店的产品有一个满足这个区间这个酒店就算满足这个条件。注意不是按酒店最低价格来过滤的。
     */
    public void setHighRate(int value) {
        this.highRate = value;
    }

    /**
     * Gets the value of the districtId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDistrictId() {
        return districtId;
    }

    /**
     * Sets the value of the districtId property.
     * 地区编码
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDistrictId(String value) {
        this.districtId = value;
    }

    /**
     * Gets the value of the businessZoneId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBusinessZoneId() {
        return businessZoneId;
    }

    /**
     * Sets the value of the businessZoneId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBusinessZoneId(String value) {
        this.businessZoneId = value;
    }

    /**
     * Gets the value of the locationId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLocationId() {
        return locationId;
    }

    /**
     * Sets the value of the locationId property.
     * 失效，不再使用
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLocationId(String value) {
        this.locationId = value;
    }

    /**
     * Gets the value of the position property.
     *
     * @return possible object is
     * {@link Position }
     */
    public Position getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     *
     * @param value allowed object is
     *              {@link Position }
     */
    public void setPosition(Position value) {
        this.position = value;
    }

    /**
     * Gets the value of the sort property.
     *
     * @return possible object is
     * {@link EnumSortType }
     */
    public EnumSortType getSort() {
        return sort;
    }

    /**
     * Sets the value of the sort property.
     * Default艺龙默认排序
     * StarRankDesc推荐星级降序
     * RateAsc价格升序
     * RateDesc价格降序
     * DistanceAsc距离升序
     *
     * @param value allowed object is
     *              {@link EnumSortType }
     */
    public void setSort(EnumSortType value) {
        this.sort = value;
    }

    /**
     * Gets the value of the pageIndex property.
     */
    public int getPageIndex() {
        return pageIndex;
    }

    /**
     * Sets the value of the pageIndex property.
     * 从1开始
     */
    public void setPageIndex(int value) {
        this.pageIndex = value;
    }

    /**
     * Gets the value of the pageSize property.
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * Sets the value of the pageSize property.
     * 取值访问：1-20
     * （PageIndex>0时PageSize为必填，否则分页失败）
     */
    public void setPageSize(int value) {
        this.pageSize = value;
    }

    /**
     * Gets the value of the customerType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * Sets the value of the customerType property.
     * None=全部;  All=统一价；Chinese =内宾价；OtherForeign =外宾价；HongKong =港澳台客人价Japanese=日本客人价
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCustomerType(String value) {
        this.customerType = value;
    }

    /**
     * Gets the value of the themeIds property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getThemeIds() {
        return themeIds;
    }

    /**
     * Sets the value of the themeIds property.
     * 97    客栈
     * 98    家庭旅馆
     * 99    青年旅舍
     * 100    精品酒店（设计师酒店）
     * 101    情侣酒店
     * 105    园林庭院
     * 103    海景
     * 106    农家乐
     * 102    温泉酒店
     * 104    高尔夫酒店
     * 107    四合院
     * 259    别墅
     * 260    聚会做饭
     * 261    商旅之家
     * 262    休闲情调
     * 265    看病就医
     * 264    度假休闲
     * 266    培训学习
     * 267    聚会
     * 268    蜜月出行
     * <p/>
     * 可以逗号分隔的组合，建议最多3个。
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setThemeIds(String value) {
        this.themeIds = value;
    }

    /**
     * Gets the value of the checkInPersonAmount property.
     */
    public int getCheckInPersonAmount() {
        return checkInPersonAmount;
    }

    /**
     * Sets the value of the checkInPersonAmount property.
     */
    public void setCheckInPersonAmount(int value) {
        this.checkInPersonAmount = value;
    }

    /**
     * Gets the value of the bedTypes property.
     * 2015.02.10增加。结果返回的酒店中将包含至少一个房间的可容纳人数大于等于该值，小于该值的房型将会过滤掉
     *
     * @return possible object is
     * {@link String }
     */
    public String getBedTypes() {
        return bedTypes;
    }

    /**
     * Sets the value of the bedTypes property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBedTypes(String value) {
        this.bedTypes = value;
    }

    /**
     * Gets the value of the resultType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getResultType() {
        return resultType;
    }

    /**
     * Sets the value of the resultType property.
     *
     * @param value allowed object is
     *              {@link String }
     *              可以是逗号分隔的组合。
     *              1.可买价格信息(房间、RP、促销、增值)
     *              2. 规则信息(预订、Drr、担保规则、预付规则)
     *              3. 酒店基本信息
     *              4. 当前不可销售的rp不出现在结果里
     *              5. 不返回Rooms、*Rules、AddValues等和产品有关系的对象
     *              6. 产品方面仅返回简单的#Products
     *              7. 返回汇率信息#ExchangeRateList
     */
    public void setResultType(String value) {
        this.resultType = value;
    }

}
