package com.data.data.hmly.service.scemanage.entity;

// Generated 2015-10-22 10:47:22 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Linedays generated by hbm2java
 */
@Entity
@Table(name = "linedays")
public class Scemanage extends com.framework.hibernate.util.Entity implements java.io.Serializable {
	private static final long serialVersionUID = -3872525549480231213L;
	private Long id;
	private Long lineId;
	private Integer lineDay;
	private String dayDesc;
	private String arrange;
	private String meals;
	private Long hotelId;
	private String hotelName;
	private Long userId;
	private Date createTime;
	private Float cost;
	private Integer travelTime;
	private Integer planTime;
	
	// 页面字段
	private List<String> meal;

	public Scemanage() {
	}

	public Scemanage(Long lineId, Integer lineDay, String dayDesc,
			String arrange, String meals, Long hotelId, String hotelName,
			Long userId, Date createTime, Float cost, Integer travelTime,
			Integer planTime) {
		this.lineId = lineId;
		this.lineDay = lineDay;
		this.dayDesc = dayDesc;
		this.arrange = arrange;
		this.meals = meals;
		this.hotelId = hotelId;
		this.hotelName = hotelName;
		this.userId = userId;
		this.createTime = createTime;
		this.cost = cost;
		this.travelTime = travelTime;
		this.planTime = planTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
}
