//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.02 at 07:34:20 PM CST 
//


package com.data.data.hmly.service.ctripticket.pojo.resp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LabelSatisticsDTOType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LabelSatisticsDTOType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LableType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="NewDestinationNavIDs"/>
 *               &lt;enumeration value="ProductDistrict"/>
 *               &lt;enumeration value="ProductCategory"/>
 *               &lt;enumeration value="MD_ScenicSpotFilterLabelGroup_ClassLabel"/>
 *               &lt;enumeration value="MD_ScenicSpotFilterLabelGroup_ThemeLabel"/>
 *               &lt;enumeration value="MD_ScenicSpotFilterLabelGroup_Themes"/>
 *               &lt;enumeration value="PayMode"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SubLabelSatistics" type="{}SubLabelSatisticsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LabelSatisticsDTOType", propOrder = {
    "lableType",
    "subLabelSatistics"
})
public class LabelSatisticsDTOType {

    @XmlElement(name = "LableType", required = true)
    protected String lableType;
    @XmlElement(name = "SubLabelSatistics", required = true)
    protected SubLabelSatisticsType subLabelSatistics;

    /**
     * Gets the value of the lableType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLableType() {
        return lableType;
    }

    /**
     * Sets the value of the lableType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLableType(String value) {
        this.lableType = value;
    }

    /**
     * Gets the value of the subLabelSatistics property.
     * 
     * @return
     *     possible object is
     *     {@link SubLabelSatisticsType }
     *     
     */
    public SubLabelSatisticsType getSubLabelSatistics() {
        return subLabelSatistics;
    }

    /**
     * Sets the value of the subLabelSatistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubLabelSatisticsType }
     *     
     */
    public void setSubLabelSatistics(SubLabelSatisticsType value) {
        this.subLabelSatistics = value;
    }

}
