//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.02 at 07:34:20 PM CST 
//


package com.data.data.hmly.service.ctripticket.pojo.resp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductListItemDTOType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductListItemDTOType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="1662296"/>
 *               &lt;enumeration value="2115430"/>
 *               &lt;enumeration value="2551677"/>
 *               &lt;enumeration value="1642708"/>
 *               &lt;enumeration value="2182859"/>
 *               &lt;enumeration value="1851832"/>
 *               &lt;enumeration value="1710521"/>
 *               &lt;enumeration value="1648051"/>
 *               &lt;enumeration value="2009358"/>
 *               &lt;enumeration value="90928"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Name">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="�������¹���Ȫ��Ʊ"/>
 *               &lt;enumeration value="���ź���ɽ��̨��Ʊ"/>
 *               &lt;enumeration value="������ܰ��/�����촬Ʊ"/>
 *               &lt;enumeration value="�����쾰����Ʊ �� �����촬Ʊ"/>
 *               &lt;enumeration value="�������չ�����Ʊ"/>
 *               &lt;enumeration value="������ɽ·���н�"/>
 *               &lt;enumeration value="���ź��Ͽ�������Ʊ"/>
 *               &lt;enumeration value="���żθ�԰��Ʊ"/>
 *               &lt;enumeration value="�����챴���λ�������Ʊ"/>
 *               &lt;enumeration value="�����ؽ�ҹ����Ʊ���ֶ���ͷ�� "/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PayMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ResourceListItemList" type="{}ResourceListItemListType"/>
 *         &lt;element name="WorkEndTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdvanceBookingDays" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdvanceBookingTime">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="22:00"/>
 *               &lt;enumeration value="16:00"/>
 *               &lt;enumeration value="17:30"/>
 *               &lt;enumeration value="17:00"/>
 *               &lt;enumeration value="15:00"/>
 *               &lt;enumeration value="16:30"/>
 *               &lt;enumeration value="20:00"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CanBookingFirstDate">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="2015-12-02T22:00:00"/>
 *               &lt;enumeration value="2015-12-03T16:00:00"/>
 *               &lt;enumeration value="2015-12-03T13:45:00"/>
 *               &lt;enumeration value="2015-12-03T14:00:00"/>
 *               &lt;enumeration value="2015-12-03T15:00:00"/>
 *               &lt;enumeration value="2015-12-03T16:30:00"/>
 *               &lt;enumeration value="2015-12-02T20:00:00"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IsMaster" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsReturnCash" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MarketPrice">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="468"/>
 *               &lt;enumeration value="25"/>
 *               &lt;enumeration value="50"/>
 *               &lt;enumeration value="60"/>
 *               &lt;enumeration value="100"/>
 *               &lt;enumeration value="20"/>
 *               &lt;enumeration value="138"/>
 *               &lt;enumeration value="30"/>
 *               &lt;enumeration value="43"/>
 *               &lt;enumeration value="136"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Price">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="99"/>
 *               &lt;enumeration value="23"/>
 *               &lt;enumeration value="18"/>
 *               &lt;enumeration value="42"/>
 *               &lt;enumeration value="90"/>
 *               &lt;enumeration value="15"/>
 *               &lt;enumeration value="80"/>
 *               &lt;enumeration value="24"/>
 *               &lt;enumeration value="39"/>
 *               &lt;enumeration value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PromotionInfoList" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReturnCashAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TicketGroupAttributes" type="{}TicketGroupAttributesType"/>
 *         &lt;element name="CategoryID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductListItemDTOType", propOrder = {
    "id",
    "name",
    "payMode",
    "resourceListItemList",
    "workEndTime",
    "advanceBookingDays",
    "advanceBookingTime",
    "canBookingFirstDate",
    "isMaster",
    "isReturnCash",
    "marketPrice",
    "price",
    "promotionInfoList",
    "returnCashAmount",
    "ticketGroupAttributes",
    "categoryID"
})
public class ProductListItemDTOType {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "PayMode", required = true)
    protected String payMode;
    @XmlElement(name = "ResourceListItemList", required = true)
    protected ResourceListItemListType resourceListItemList;
    @XmlElement(name = "WorkEndTime", required = true)
    protected String workEndTime;
    @XmlElement(name = "AdvanceBookingDays", required = true)
    protected String advanceBookingDays;
    @XmlElement(name = "AdvanceBookingTime", required = true)
    protected String advanceBookingTime;
    @XmlElement(name = "CanBookingFirstDate", required = true)
    protected String canBookingFirstDate;
    @XmlElement(name = "IsMaster", required = true)
    protected String isMaster;
    @XmlElement(name = "IsReturnCash", required = true)
    protected String isReturnCash;
    @XmlElement(name = "MarketPrice", required = true)
    protected String marketPrice;
    @XmlElement(name = "Price", required = true)
    protected String price;
    @XmlElement(name = "PromotionInfoList", required = true)
    protected String promotionInfoList;
    @XmlElement(name = "ReturnCashAmount", required = true)
    protected String returnCashAmount;
    @XmlElement(name = "TicketGroupAttributes", required = true)
    protected TicketGroupAttributesType ticketGroupAttributes;
    @XmlElement(name = "CategoryID", required = true)
    protected String categoryID;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the payMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayMode() {
        return payMode;
    }

    /**
     * Sets the value of the payMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayMode(String value) {
        this.payMode = value;
    }

    /**
     * Gets the value of the resourceListItemList property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceListItemListType }
     *     
     */
    public ResourceListItemListType getResourceListItemList() {
        return resourceListItemList;
    }

    /**
     * Sets the value of the resourceListItemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceListItemListType }
     *     
     */
    public void setResourceListItemList(ResourceListItemListType value) {
        this.resourceListItemList = value;
    }

    /**
     * Gets the value of the workEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkEndTime() {
        return workEndTime;
    }

    /**
     * Sets the value of the workEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkEndTime(String value) {
        this.workEndTime = value;
    }

    /**
     * Gets the value of the advanceBookingDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvanceBookingDays() {
        return advanceBookingDays;
    }

    /**
     * Sets the value of the advanceBookingDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvanceBookingDays(String value) {
        this.advanceBookingDays = value;
    }

    /**
     * Gets the value of the advanceBookingTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvanceBookingTime() {
        return advanceBookingTime;
    }

    /**
     * Sets the value of the advanceBookingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvanceBookingTime(String value) {
        this.advanceBookingTime = value;
    }

    /**
     * Gets the value of the canBookingFirstDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanBookingFirstDate() {
        return canBookingFirstDate;
    }

    /**
     * Sets the value of the canBookingFirstDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanBookingFirstDate(String value) {
        this.canBookingFirstDate = value;
    }

    /**
     * Gets the value of the isMaster property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsMaster() {
        return isMaster;
    }

    /**
     * Sets the value of the isMaster property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsMaster(String value) {
        this.isMaster = value;
    }

    /**
     * Gets the value of the isReturnCash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsReturnCash() {
        return isReturnCash;
    }

    /**
     * Sets the value of the isReturnCash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsReturnCash(String value) {
        this.isReturnCash = value;
    }

    /**
     * Gets the value of the marketPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketPrice() {
        return marketPrice;
    }

    /**
     * Sets the value of the marketPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketPrice(String value) {
        this.marketPrice = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrice(String value) {
        this.price = value;
    }

    /**
     * Gets the value of the promotionInfoList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromotionInfoList() {
        return promotionInfoList;
    }

    /**
     * Sets the value of the promotionInfoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromotionInfoList(String value) {
        this.promotionInfoList = value;
    }

    /**
     * Gets the value of the returnCashAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnCashAmount() {
        return returnCashAmount;
    }

    /**
     * Sets the value of the returnCashAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnCashAmount(String value) {
        this.returnCashAmount = value;
    }

    /**
     * Gets the value of the ticketGroupAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link TicketGroupAttributesType }
     *     
     */
    public TicketGroupAttributesType getTicketGroupAttributes() {
        return ticketGroupAttributes;
    }

    /**
     * Sets the value of the ticketGroupAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketGroupAttributesType }
     *     
     */
    public void setTicketGroupAttributes(TicketGroupAttributesType value) {
        this.ticketGroupAttributes = value;
    }

    /**
     * Gets the value of the categoryID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryID() {
        return categoryID;
    }

    /**
     * Sets the value of the categoryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryID(String value) {
        this.categoryID = value;
    }

}
