//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.02 at 07:34:20 PM CST 
//


package com.data.data.hmly.service.ctripticket.pojo.resp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ResourceListItemDTOType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceListItemDTOType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CategoryID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ExchangeMode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsHighRisk" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsReturnCash" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MarketPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PayMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReturnCashAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TicketDistributionChannel" type="{}TicketDistributionChannelType"/>
 *         &lt;element name="TicketGroupAttributes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TicketAttributeGroupDTO" type="{}TicketAttributeGroupDTOType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TicketType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PeopleGroup">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="32"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UnitQuantity">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SaleTag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceListItemDTOType", propOrder = {
    "categoryID",
    "exchangeMode",
    "id",
    "isHighRisk",
    "isReturnCash",
    "marketPrice",
    "name",
    "payMode",
    "price",
    "returnCashAmount",
    "ticketDistributionChannel",
    "ticketGroupAttributes",
    "ticketType",
    "peopleGroup",
    "unitQuantity",
    "saleTag"
})
public class ResourceListItemDTOType {

    @XmlElement(name = "CategoryID", required = true)
    protected String categoryID;
    @XmlElement(name = "ExchangeMode", required = true)
    protected String exchangeMode;
    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "IsHighRisk", required = true)
    protected String isHighRisk;
    @XmlElement(name = "IsReturnCash", required = true)
    protected String isReturnCash;
    @XmlElement(name = "MarketPrice", required = true)
    protected String marketPrice;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "PayMode", required = true)
    protected String payMode;
    @XmlElement(name = "Price", required = true)
    protected String price;
    @XmlElement(name = "ReturnCashAmount", required = true)
    protected String returnCashAmount;
    @XmlElement(name = "TicketDistributionChannel", required = true)
    protected TicketDistributionChannelType ticketDistributionChannel;
    @XmlElement(name = "TicketGroupAttributes", required = true)
    protected ResourceListItemDTOType.TicketGroupAttributes ticketGroupAttributes;
    @XmlElement(name = "TicketType", required = true)
    protected String ticketType;
    @XmlElement(name = "PeopleGroup", required = true)
    protected String peopleGroup;
    @XmlElement(name = "UnitQuantity", required = true)
    protected String unitQuantity;
    @XmlElement(name = "SaleTag")
    protected String saleTag;

    /**
     * Gets the value of the categoryID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryID() {
        return categoryID;
    }

    /**
     * Sets the value of the categoryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryID(String value) {
        this.categoryID = value;
    }

    /**
     * Gets the value of the exchangeMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeMode() {
        return exchangeMode;
    }

    /**
     * Sets the value of the exchangeMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeMode(String value) {
        this.exchangeMode = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the isHighRisk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsHighRisk() {
        return isHighRisk;
    }

    /**
     * Sets the value of the isHighRisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsHighRisk(String value) {
        this.isHighRisk = value;
    }

    /**
     * Gets the value of the isReturnCash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsReturnCash() {
        return isReturnCash;
    }

    /**
     * Sets the value of the isReturnCash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsReturnCash(String value) {
        this.isReturnCash = value;
    }

    /**
     * Gets the value of the marketPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketPrice() {
        return marketPrice;
    }

    /**
     * Sets the value of the marketPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketPrice(String value) {
        this.marketPrice = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the payMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayMode() {
        return payMode;
    }

    /**
     * Sets the value of the payMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayMode(String value) {
        this.payMode = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrice(String value) {
        this.price = value;
    }

    /**
     * Gets the value of the returnCashAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnCashAmount() {
        return returnCashAmount;
    }

    /**
     * Sets the value of the returnCashAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnCashAmount(String value) {
        this.returnCashAmount = value;
    }

    /**
     * Gets the value of the ticketDistributionChannel property.
     * 
     * @return
     *     possible object is
     *     {@link TicketDistributionChannelType }
     *     
     */
    public TicketDistributionChannelType getTicketDistributionChannel() {
        return ticketDistributionChannel;
    }

    /**
     * Sets the value of the ticketDistributionChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketDistributionChannelType }
     *     
     */
    public void setTicketDistributionChannel(TicketDistributionChannelType value) {
        this.ticketDistributionChannel = value;
    }

    /**
     * Gets the value of the ticketGroupAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceListItemDTOType.TicketGroupAttributes }
     *     
     */
    public ResourceListItemDTOType.TicketGroupAttributes getTicketGroupAttributes() {
        return ticketGroupAttributes;
    }

    /**
     * Sets the value of the ticketGroupAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceListItemDTOType.TicketGroupAttributes }
     *     
     */
    public void setTicketGroupAttributes(ResourceListItemDTOType.TicketGroupAttributes value) {
        this.ticketGroupAttributes = value;
    }

    /**
     * Gets the value of the ticketType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketType() {
        return ticketType;
    }

    /**
     * Sets the value of the ticketType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketType(String value) {
        this.ticketType = value;
    }

    /**
     * Gets the value of the peopleGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeopleGroup() {
        return peopleGroup;
    }

    /**
     * Sets the value of the peopleGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeopleGroup(String value) {
        this.peopleGroup = value;
    }

    /**
     * Gets the value of the unitQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitQuantity() {
        return unitQuantity;
    }

    /**
     * Sets the value of the unitQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitQuantity(String value) {
        this.unitQuantity = value;
    }

    /**
     * Gets the value of the saleTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaleTag() {
        return saleTag;
    }

    /**
     * Sets the value of the saleTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaleTag(String value) {
        this.saleTag = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TicketAttributeGroupDTO" type="{}TicketAttributeGroupDTOType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ticketAttributeGroupDTO"
    })
    public static class TicketGroupAttributes {

        @XmlElement(name = "TicketAttributeGroupDTO")
        protected List<TicketAttributeGroupDTOType> ticketAttributeGroupDTO;

        /**
         * Gets the value of the ticketAttributeGroupDTO property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ticketAttributeGroupDTO property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTicketAttributeGroupDTO().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TicketAttributeGroupDTOType }
         * 
         * 
         */
        public List<TicketAttributeGroupDTOType> getTicketAttributeGroupDTO() {
            if (ticketAttributeGroupDTO == null) {
                ticketAttributeGroupDTO = new ArrayList<TicketAttributeGroupDTOType>();
            }
            return this.ticketAttributeGroupDTO;
        }

    }

}
