//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.02 at 07:34:20 PM CST 
//


package com.data.data.hmly.service.ctripticket.pojo.resp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScenicSpotSearchResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScenicSpotSearchResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LabelSatistics" type="{}LabelSatisticsType"/>
 *         &lt;element name="PagingCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RowCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ScenicSpotListItemList" type="{}ScenicSpotListItemListType"/>
 *         &lt;element name="TabTypeSatistics" type="{}TabTypeSatisticsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseBodyType", propOrder = {
    "ScenicSpotSearchResponse"
})
public class ResponseBodyType {

    @XmlElement(name = "ScenicSpotSearchResponse", required = true)
    protected ScenicSpotSearchResponseType ScenicSpotSearchResponse;

	public ScenicSpotSearchResponseType getScenicSpotSearchResponse() {
		return ScenicSpotSearchResponse;
	}

	public void setScenicSpotSearchResponse(
			ScenicSpotSearchResponseType scenicSpotSearchResponse) {
		ScenicSpotSearchResponse = scenicSpotSearchResponse;
	}

}
