//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.02 at 07:34:20 PM CST 
//


package com.data.data.hmly.service.ctripticket.pojo.resp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TabTypeSatisticsDTOType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TabTypeSatisticsDTOType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Count" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TabTypeShow" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TabTypeSatisticsDTOType", propOrder = {
    "count",
    "tabTypeShow"
})
public class TabTypeSatisticsDTOType {

    @XmlElement(name = "Count", required = true)
    protected String count;
    @XmlElement(name = "TabTypeShow", required = true)
    protected String tabTypeShow;

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCount(String value) {
        this.count = value;
    }

    /**
     * Gets the value of the tabTypeShow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTabTypeShow() {
        return tabTypeShow;
    }

    /**
     * Sets the value of the tabTypeShow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTabTypeShow(String value) {
        this.tabTypeShow = value;
    }

}
