//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 05:35:30 PM CST 
//


package com.data.data.hmly.service.ctripticket.pojo.resp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ProductID"/>
 *         &lt;element ref="{}ResourceID"/>
 *         &lt;element ref="{}ResourcePriceAndInventoryDailyList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productID",
    "resourceID",
    "resourcePriceAndInventoryDailyList"
})
@XmlRootElement(name = "TicketPriceSearchResponseDetail")
public class TrpaiTicketPriceSearchResponseDetail {

    @XmlElement(name = "ProductID", required = true)
    protected BigInteger productID;
    @XmlElement(name = "ResourceID", required = true)
    protected BigInteger resourceID;
    @XmlElement(name = "ResourcePriceAndInventoryDailyList", required = true)
    protected TrpaiResourcePriceAndInventoryDailyList resourcePriceAndInventoryDailyList;

    /**
     * Gets the value of the productID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProductID() {
        return productID;
    }

    /**
     * Sets the value of the productID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProductID(BigInteger value) {
        this.productID = value;
    }

    /**
     * Gets the value of the resourceID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getResourceID() {
        return resourceID;
    }

    /**
     * Sets the value of the resourceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setResourceID(BigInteger value) {
        this.resourceID = value;
    }

    /**
     * Gets the value of the resourcePriceAndInventoryDailyList property.
     * 
     * @return
     *     possible object is
     *     {@link TrpaiResourcePriceAndInventoryDailyList }
     *     
     */
    public TrpaiResourcePriceAndInventoryDailyList getResourcePriceAndInventoryDailyList() {
        return resourcePriceAndInventoryDailyList;
    }

    /**
     * Sets the value of the resourcePriceAndInventoryDailyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrpaiResourcePriceAndInventoryDailyList }
     *     
     */
    public void setResourcePriceAndInventoryDailyList(TrpaiResourcePriceAndInventoryDailyList value) {
        this.resourcePriceAndInventoryDailyList = value;
    }

}
