//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 11:28:15 AM CST 
//


package com.data.data.hmly.service.ctripticket.pojo.req;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MasterTicketDTO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "masterTicketDTO"
})
@XmlRootElement(name = "TicketInfo")
public class TocfpTicketInfo {

    @XmlElement(name = "MasterTicketDTO", required = true)
    protected List<TocfpMasterTicketDTO> masterTicketDTO;
//    protected TocfpMasterTicketDTO masterTicketDTO;

    public List<TocfpMasterTicketDTO> getMasterTicketDTO() {
        if (masterTicketDTO == null) {
        	masterTicketDTO = new ArrayList<TocfpMasterTicketDTO>();
        }
        return this.masterTicketDTO;
    }

	public void setMasterTicketDTO(List<TocfpMasterTicketDTO> masterTicketDTO) {
		this.masterTicketDTO = masterTicketDTO;
	}

}
