//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 11:28:15 AM CST 
//


package com.data.data.hmly.service.ctripticket.pojo.req;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}AgeType"/>
 *         &lt;element ref="{}BirthDate"/>
 *         &lt;element ref="{}ClientName"/>
 *         &lt;element ref="{}ClientName_E"/>
 *         &lt;element ref="{}ContactInfo"/>
 *         &lt;element ref="{}Gender"/>
 *         &lt;element ref="{}HzDate"/>
 *         &lt;element ref="{}HzNo"/>
 *         &lt;element ref="{}IDCardNo"/>
 *         &lt;element ref="{}IDCardTimelimit"/>
 *         &lt;element ref="{}IDCardType"/>
 *         &lt;element ref="{}InfoID"/>
 *         &lt;element ref="{}IssueDate"/>
 *         &lt;element ref="{}PassportType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ageType",
    "birthDate",
    "clientName",
    "clientNameE",
    "contactInfo",
    "gender",
    "hzDate",
    "hzNo",
    "idCardNo",
    "idCardTimelimit",
    "idCardType",
    "infoID",
    "issueDate",
    "passportType"
})
@XmlRootElement(name = "ClientDTO")
public class TocfpClientDTO {

    @XmlElement(name = "AgeType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ageType;
    @XmlElement(name = "BirthDate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String birthDate;
    @XmlElement(name = "ClientName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String clientName;
    @XmlElement(name = "ClientName_E", required = true)
    protected String clientNameE;
    @XmlElement(name = "ContactInfo", required = true)
    protected String contactInfo;
    @XmlElement(name = "Gender", required = true)
    protected String gender;
    @XmlElement(name = "HzDate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String hzDate;
    @XmlElement(name = "HzNo", required = true)
    protected String hzNo;
    @XmlElement(name = "IDCardNo", required = true)
    protected String idCardNo;
    @XmlElement(name = "IDCardTimelimit", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String idCardTimelimit;
    @XmlElement(name = "IDCardType", required = true)
    protected Integer idCardType;
    @XmlElement(name = "InfoID", required = true)
    protected Integer infoID;
    @XmlElement(name = "IssueDate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String issueDate;
    @XmlElement(name = "PassportType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String passportType;

    /**
     * Gets the value of the ageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgeType() {
        return ageType;
    }

    /**
     * Sets the value of the ageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgeType(String value) {
        this.ageType = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthDate(String value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the clientName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * Sets the value of the clientName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientName(String value) {
        this.clientName = value;
    }

    /**
     * Gets the value of the clientNameE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientNameE() {
        return clientNameE;
    }

    /**
     * Sets the value of the clientNameE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientNameE(String value) {
        this.clientNameE = value;
    }

    /**
     * Gets the value of the contactInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TocfpContactInfo }
     *     
     */
    public String getContactInfo() {
        return contactInfo;
    }

    /**
     * Sets the value of the contactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TocfpContactInfo }
     *     
     */
    public void setContactInfo(String value) {
        this.contactInfo = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the hzDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHzDate() {
        return hzDate;
    }

    /**
     * Sets the value of the hzDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHzDate(String value) {
        this.hzDate = value;
    }

    /**
     * Gets the value of the hzNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getHzNo() {
        return hzNo;
    }

    /**
     * Sets the value of the hzNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHzNo(String value) {
        this.hzNo = value;
    }

    /**
     * Gets the value of the idCardNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getIDCardNo() {
        return idCardNo;
    }

    /**
     * Sets the value of the idCardNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIDCardNo(String value) {
        this.idCardNo = value;
    }

    /**
     * Gets the value of the idCardTimelimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDCardTimelimit() {
        return idCardTimelimit;
    }

    /**
     * Sets the value of the idCardTimelimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDCardTimelimit(String value) {
        this.idCardTimelimit = value;
    }

    /**
     * Gets the value of the idCardType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public Integer getIDCardType() {
        return idCardType;
    }

    /**
     * Sets the value of the idCardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIDCardType(Integer value) {
        this.idCardType = value;
    }

    /**
     * Gets the value of the infoID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public Integer getInfoID() {
        return infoID;
    }

    /**
     * Sets the value of the infoID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInfoID(Integer value) {
        this.infoID = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueDate(String value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the passportType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassportType() {
        return passportType;
    }

    /**
     * Sets the value of the passportType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassportType(String value) {
        this.passportType = value;
    }

}
