//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 11:28:15 AM CST 
//


package com.data.data.hmly.service.ctripticket.pojo.req;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}AdultNumber"/>
 *         &lt;element ref="{}Amount"/>
 *         &lt;element ref="{}ClientInfoList"/>
 *         &lt;element ref="{}DistributorOrderID"/>
 *         &lt;element ref="{}ContactInfo"/>
 *         &lt;element ref="{}ProductInfo"/>
 *         &lt;element ref="{}Remark"/>
 *         &lt;element ref="{}SalesCity"/>
 *         &lt;element ref="{}TicketInfo"/>
 *         &lt;element ref="{}Uid"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "adultNumber",
    "amount",
    "childNumber",
    "clientInfoList",
    "distributorOrderID",
//    "contactInfo",
    "productInfo",
    "remark",
    "salesCity",
    "ticketInfo",
    "uid"
})
@XmlRootElement(name = "TicketOrderCreateRequest")
public class TocfpTicketOrderCreateRequest {

    @XmlElement(name = "AdultNumber", required = true)
    protected Integer adultNumber;
    @XmlElement(name = "Amount", required = true)
    protected Integer amount;
    @XmlElement(name = "ChildNumber", required = true)
    protected Integer childNumber;
    @XmlElement(name = "ClientInfoList", required = true)
    protected TocfpClientInfoList clientInfoList;
    @XmlElement(name = "DistributorOrderID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String distributorOrderID;
//    @XmlElement(name = "ContactInfo", required = true)
//    protected TocfpContactInfo contactInfo;
    @XmlElement(name = "ProductInfo", required = true)
    protected TocfpProductInfo productInfo;
    @XmlElement(name = "Remark", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String remark;
    @XmlElement(name = "SalesCity", required = true)
    protected Integer salesCity;
    @XmlElement(name = "TicketInfo", required = true)
    protected TocfpTicketInfo ticketInfo;
    @XmlElement(name = "Uid", required = true)
    protected String uid;

    /**
     * Gets the value of the adultNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public Integer getAdultNumber() {
        return adultNumber;
    }

    /**
     * Sets the value of the adultNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAdultNumber(Integer value) {
        this.adultNumber = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAmount(Integer value) {
        this.amount = value;
    }

	public Integer getChildNumber() {
		return childNumber;
	}

	public void setChildNumber(Integer childNumber) {
		this.childNumber = childNumber;
	}

	/**
     * Gets the value of the clientInfoList property.
     * 
     * @return
     *     possible object is
     *     {@link TocfpClientInfoList }
     *     
     */
    public TocfpClientInfoList getClientInfoList() {
        return clientInfoList;
    }

    /**
     * Sets the value of the clientInfoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TocfpClientInfoList }
     *     
     */
    public void setClientInfoList(TocfpClientInfoList value) {
        this.clientInfoList = value;
    }

    /**
     * Gets the value of the distributorOrderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistributorOrderID() {
        return distributorOrderID;
    }

    /**
     * Sets the value of the distributorOrderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistributorOrderID(String value) {
        this.distributorOrderID = value;
    }

    /**
     * Gets the value of the contactInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TocfpContactInfo }
     *     
     */
//    public TocfpContactInfo getContactInfo() {
//        return contactInfo;
//    }

    /**
     * Sets the value of the contactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TocfpContactInfo }
     *     
     */
//    public void setContactInfo(TocfpContactInfo value) {
//        this.contactInfo = value;
//    }

    /**
     * Gets the value of the productInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TocfpProductInfo }
     *     
     */
    public TocfpProductInfo getProductInfo() {
        return productInfo;
    }

    /**
     * Sets the value of the productInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TocfpProductInfo }
     *     
     */
    public void setProductInfo(TocfpProductInfo value) {
        this.productInfo = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemark(String value) {
        this.remark = value;
    }

    /**
     * Gets the value of the salesCity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public Integer getSalesCity() {
        return salesCity;
    }

    /**
     * Sets the value of the salesCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSalesCity(Integer value) {
        this.salesCity = value;
    }

    /**
     * Gets the value of the ticketInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TocfpTicketInfo }
     *     
     */
    public TocfpTicketInfo getTicketInfo() {
        return ticketInfo;
    }

    /**
     * Sets the value of the ticketInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TocfpTicketInfo }
     *     
     */
    public void setTicketInfo(TocfpTicketInfo value) {
        this.ticketInfo = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

}
