//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 03:36:59 PM CST 
//


package com.data.data.hmly.service.ctripflight.response.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FlightRoutesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightRoutesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DomesticFlightRoute" type="{}DomesticFlightRouteType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightRoutesType", propOrder = {
    "domesticFlightRoute"
})
public class FlightRoutesType {

    @XmlElement(name = "DomesticFlightRoute", required = true)
    protected DomesticFlightRouteType domesticFlightRoute;

    /**
     * Gets the value of the domesticFlightRoute property.
     * 
     * @return
     *     possible object is
     *     {@link DomesticFlightRouteType }
     *     
     */
    public DomesticFlightRouteType getDomesticFlightRoute() {
        return domesticFlightRoute;
    }

    /**
     * Sets the value of the domesticFlightRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomesticFlightRouteType }
     *     
     */
    public void setDomesticFlightRoute(DomesticFlightRouteType value) {
        this.domesticFlightRoute = value;
    }

}
