//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.06 at 12:44:44 AM CST 
//


package com.data.data.hmly.service.ctripflight.response.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PassengersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PassengersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderPassenger" type="{}OrderPassengerType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PassengersType", propOrder = {
    "orderPassenger"
})
public class FltViewOrderPassengersType {

    @XmlElement(name = "OrderPassenger", required = true)
    protected FltViewOrderPassengerType orderPassenger;

    /**
     * Gets the value of the orderPassenger property.
     * 
     * @return
     *     possible object is
     *     {@link FltViewOrderPassengerType }
     *     
     */
    public FltViewOrderPassengerType getOrderPassenger() {
        return orderPassenger;
    }

    /**
     * Sets the value of the orderPassenger property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltViewOrderPassengerType }
     *     
     */
    public void setOrderPassenger(FltViewOrderPassengerType value) {
        this.orderPassenger = value;
    }

}
