//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.06 at 12:44:44 AM CST 
//


package com.data.data.hmly.service.ctripflight.response.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class FltViewOrderObjectFactory {

    private final static QName _Response_QNAME = new QName("", "Response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public FltViewOrderObjectFactory() {
    }

    /**
     * Create an instance of {@link FltViewOrderResponse }
     * 
     */
    public FltViewOrderResponse createResponseType() {
        return new FltViewOrderResponse();
    }

    /**
     * Create an instance of {@link FltViewOrderFailedOrderType }
     * 
     */
    public FltViewOrderFailedOrderType createFailedOrderType() {
        return new FltViewOrderFailedOrderType();
    }

    /**
     * Create an instance of {@link FltViewOrderFlightsType }
     * 
     */
    public FltViewOrderFlightsType createFlightsType() {
        return new FltViewOrderFlightsType();
    }

    /**
     * Create an instance of {@link FltViewOrdersInfoType }
     * 
     */
    public FltViewOrdersInfoType createOrdersInfoType() {
        return new FltViewOrdersInfoType();
    }

    /**
     * Create an instance of {@link FltViewOrderBasicOrderInfoType }
     * 
     */
    public FltViewOrderBasicOrderInfoType createBasicOrderInfoType() {
        return new FltViewOrderBasicOrderInfoType();
    }

    /**
     * Create an instance of {@link FltViewOrderPromptsType }
     * 
     */
    public FltViewOrderPromptsType createPromptsType() {
        return new FltViewOrderPromptsType();
    }

    /**
     * Create an instance of {@link FltViewOrderPassengerType }
     * 
     */
    public FltViewOrderPassengerType createOrderPassengerType() {
        return new FltViewOrderPassengerType();
    }

    /**
     * Create an instance of {@link FltViewOrderResponseType }
     * 
     */
    public FltViewOrderResponseType createFltViewOrderResponseType() {
        return new FltViewOrderResponseType();
    }

    /**
     * Create an instance of {@link FltViewOrderHeaderType }
     * 
     */
    public FltViewOrderHeaderType createHeaderType() {
        return new FltViewOrderHeaderType();
    }

    /**
     * Create an instance of {@link FltViewOrderInfoType }
     * 
     */
    public FltViewOrderInfoType createOrderInfoType() {
        return new FltViewOrderInfoType();
    }

    /**
     * Create an instance of {@link FltViewOrderDepartAirportType }
     * 
     */
    public FltViewOrderDepartAirportType createDepartAirportType() {
        return new FltViewOrderDepartAirportType();
    }

    /**
     * Create an instance of {@link FltViewOrderArriveAirportType }
     * 
     */
    public FltViewOrderArriveAirportType createArriveAirportType() {
        return new FltViewOrderArriveAirportType();
    }

    /**
     * Create an instance of {@link FltViewOrderFlightType }
     * 
     */
    public FltViewOrderFlightType createOrderFlightType() {
        return new FltViewOrderFlightType();
    }

    /**
     * Create an instance of {@link FltViewOrderPassengersType }
     * 
     */
    public FltViewOrderPassengersType createPassengersType() {
        return new FltViewOrderPassengersType();
    }

    /**
     * Create an instance of {@link FltViewOrderDeliverType }
     * 
     */
    public FltViewOrderDeliverType createDeliverType() {
        return new FltViewOrderDeliverType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FltViewOrderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Response")
    public JAXBElement<FltViewOrderResponse> createResponse(FltViewOrderResponse value) {
        return new JAXBElement<FltViewOrderResponse>(_Response_QNAME, FltViewOrderResponse.class, null, value);
    }

}
