//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.06 at 12:44:44 AM CST 
//


package com.data.data.hmly.service.ctripflight.response.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderPassengerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderPassengerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PassengerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Birthday" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NationalityCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NationalityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CardTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CardTypeNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PassengerNamePY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CardValid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CorpEid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderPassengerType", propOrder = {
    "passengerName",
    "birthday",
    "gender",
    "nationalityCode",
    "nationalityName",
    "cardTypeName",
    "cardTypeNumber",
    "passengerNamePY",
    "cardValid",
    "corpEid"
})
public class FltViewOrderPassengerType {

    @XmlElement(name = "PassengerName", required = true)
    protected String passengerName;
    @XmlElement(name = "Birthday", required = true)
    protected String birthday;
    @XmlElement(name = "Gender", required = true)
    protected String gender;
    @XmlElement(name = "NationalityCode", required = true)
    protected String nationalityCode;
    @XmlElement(name = "NationalityName", required = true)
    protected String nationalityName;
    @XmlElement(name = "CardTypeName", required = true)
    protected String cardTypeName;
    @XmlElement(name = "CardTypeNumber", required = true)
    protected String cardTypeNumber;
    @XmlElement(name = "PassengerNamePY", required = true)
    protected String passengerNamePY;
    @XmlElement(name = "CardValid", required = true)
    protected String cardValid;
    @XmlElement(name = "CorpEid", required = true)
    protected String corpEid;

    /**
     * Gets the value of the passengerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassengerName() {
        return passengerName;
    }

    /**
     * Sets the value of the passengerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassengerName(String value) {
        this.passengerName = value;
    }

    /**
     * Gets the value of the birthday property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * Sets the value of the birthday property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthday(String value) {
        this.birthday = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the nationalityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalityCode() {
        return nationalityCode;
    }

    /**
     * Sets the value of the nationalityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalityCode(String value) {
        this.nationalityCode = value;
    }

    /**
     * Gets the value of the nationalityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalityName() {
        return nationalityName;
    }

    /**
     * Sets the value of the nationalityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalityName(String value) {
        this.nationalityName = value;
    }

    /**
     * Gets the value of the cardTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardTypeName() {
        return cardTypeName;
    }

    /**
     * Sets the value of the cardTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardTypeName(String value) {
        this.cardTypeName = value;
    }

    /**
     * Gets the value of the cardTypeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardTypeNumber() {
        return cardTypeNumber;
    }

    /**
     * Sets the value of the cardTypeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardTypeNumber(String value) {
        this.cardTypeNumber = value;
    }

    /**
     * Gets the value of the passengerNamePY property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassengerNamePY() {
        return passengerNamePY;
    }

    /**
     * Sets the value of the passengerNamePY property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassengerNamePY(String value) {
        this.passengerNamePY = value;
    }

    /**
     * Gets the value of the cardValid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardValid() {
        return cardValid;
    }

    /**
     * Sets the value of the cardValid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardValid(String value) {
        this.cardValid = value;
    }

    /**
     * Gets the value of the corpEid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorpEid() {
        return corpEid;
    }

    /**
     * Sets the value of the corpEid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorpEid(String value) {
        this.corpEid = value;
    }

}
