//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.06 at 12:44:44 AM CST 
//


package com.data.data.hmly.service.ctripflight.response.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BasicOrderInfo" type="{}BasicOrderInfoType"/>
 *         &lt;element name="Flights" type="{}FlightsType"/>
 *         &lt;element name="Passengers" type="{}PassengersType"/>
 *         &lt;element name="Deliver" type="{}DeliverType"/>
 *         &lt;element name="StopsInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Prompts" type="{}PromptsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderInfoType", propOrder = {
    "basicOrderInfo",
    "flights",
    "passengers",
    "deliver",
    "stopsInfo",
    "prompts"
})
public class FltViewOrderInfoType {

    @XmlElement(name = "BasicOrderInfo", required = true)
    protected FltViewOrderBasicOrderInfoType basicOrderInfo;
    @XmlElement(name = "Flights", required = true)
    protected FltViewOrderFlightsType flights;
    @XmlElement(name = "Passengers", required = true)
    protected FltViewOrderPassengersType passengers;
    @XmlElement(name = "Deliver", required = true)
    protected FltViewOrderDeliverType deliver;
    @XmlElement(name = "StopsInfo", required = true)
    protected String stopsInfo;
    @XmlElement(name = "Prompts", required = true)
    protected FltViewOrderPromptsType prompts;

    /**
     * Gets the value of the basicOrderInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FltViewOrderBasicOrderInfoType }
     *     
     */
    public FltViewOrderBasicOrderInfoType getBasicOrderInfo() {
        return basicOrderInfo;
    }

    /**
     * Sets the value of the basicOrderInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltViewOrderBasicOrderInfoType }
     *     
     */
    public void setBasicOrderInfo(FltViewOrderBasicOrderInfoType value) {
        this.basicOrderInfo = value;
    }

    /**
     * Gets the value of the flights property.
     * 
     * @return
     *     possible object is
     *     {@link FltViewOrderFlightsType }
     *     
     */
    public FltViewOrderFlightsType getFlights() {
        return flights;
    }

    /**
     * Sets the value of the flights property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltViewOrderFlightsType }
     *     
     */
    public void setFlights(FltViewOrderFlightsType value) {
        this.flights = value;
    }

    /**
     * Gets the value of the passengers property.
     * 
     * @return
     *     possible object is
     *     {@link FltViewOrderPassengersType }
     *     
     */
    public FltViewOrderPassengersType getPassengers() {
        return passengers;
    }

    /**
     * Sets the value of the passengers property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltViewOrderPassengersType }
     *     
     */
    public void setPassengers(FltViewOrderPassengersType value) {
        this.passengers = value;
    }

    /**
     * Gets the value of the deliver property.
     * 
     * @return
     *     possible object is
     *     {@link FltViewOrderDeliverType }
     *     
     */
    public FltViewOrderDeliverType getDeliver() {
        return deliver;
    }

    /**
     * Sets the value of the deliver property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltViewOrderDeliverType }
     *     
     */
    public void setDeliver(FltViewOrderDeliverType value) {
        this.deliver = value;
    }

    /**
     * Gets the value of the stopsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopsInfo() {
        return stopsInfo;
    }

    /**
     * Sets the value of the stopsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopsInfo(String value) {
        this.stopsInfo = value;
    }

    /**
     * Gets the value of the prompts property.
     * 
     * @return
     *     possible object is
     *     {@link FltViewOrderPromptsType }
     *     
     */
    public FltViewOrderPromptsType getPrompts() {
        return prompts;
    }

    /**
     * Sets the value of the prompts property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltViewOrderPromptsType }
     *     
     */
    public void setPrompts(FltViewOrderPromptsType value) {
        this.prompts = value;
    }

}
