//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.07 at 05:05:05 PM CST 
//


package com.data.data.hmly.service.ctripflight.response.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AirlineInfoEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AirlineInfoEntityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AirLine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AirLineCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AirLineName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GroupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StrictType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AddonPriceProtected" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsSupportAirPlus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="T"/>
 *               &lt;enumeration value="F"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OnlineCheckinUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AirlineInfoEntityType", propOrder = {
    "airLine",
    "airLineCode",
    "airLineName",
    "shortName",
    "groupId",
    "strictType",
    "addonPriceProtected",
    "isSupportAirPlus",
    "onlineCheckinUrl"
})
public class GetAirlineInfoEntityType {

    @XmlElement(name = "AirLine", required = true)
    protected String airLine;
    @XmlElement(name = "AirLineCode", required = true)
    protected String airLineCode;
    @XmlElement(name = "AirLineName", required = true)
    protected String airLineName;
    @XmlElement(name = "ShortName", required = true)
    protected String shortName;
    @XmlElement(name = "GroupId", required = true)
    protected String groupId;
    @XmlElement(name = "StrictType", required = true)
    protected String strictType;
    @XmlElement(name = "AddonPriceProtected", required = true)
    protected String addonPriceProtected;
    @XmlElement(name = "IsSupportAirPlus", required = true)
    protected String isSupportAirPlus;
    @XmlElement(name = "OnlineCheckinUrl", required = true)
    protected String onlineCheckinUrl;

    /**
     * Gets the value of the airLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirLine() {
        return airLine;
    }

    /**
     * Sets the value of the airLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirLine(String value) {
        this.airLine = value;
    }

    /**
     * Gets the value of the airLineCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirLineCode() {
        return airLineCode;
    }

    /**
     * Sets the value of the airLineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirLineCode(String value) {
        this.airLineCode = value;
    }

    /**
     * Gets the value of the airLineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirLineName() {
        return airLineName;
    }

    /**
     * Sets the value of the airLineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirLineName(String value) {
        this.airLineName = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the strictType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrictType() {
        return strictType;
    }

    /**
     * Sets the value of the strictType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrictType(String value) {
        this.strictType = value;
    }

    /**
     * Gets the value of the addonPriceProtected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddonPriceProtected() {
        return addonPriceProtected;
    }

    /**
     * Sets the value of the addonPriceProtected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddonPriceProtected(String value) {
        this.addonPriceProtected = value;
    }

    /**
     * Gets the value of the isSupportAirPlus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsSupportAirPlus() {
        return isSupportAirPlus;
    }

    /**
     * Sets the value of the isSupportAirPlus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsSupportAirPlus(String value) {
        this.isSupportAirPlus = value;
    }

    /**
     * Gets the value of the onlineCheckinUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnlineCheckinUrl() {
        return onlineCheckinUrl;
    }

    /**
     * Sets the value of the onlineCheckinUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnlineCheckinUrl(String value) {
        this.onlineCheckinUrl = value;
    }

}
