//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.07 at 06:06:50 PM CST 
//


package com.data.data.hmly.service.ctripflight.response.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CraftInfoEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CraftInfoEntityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CraftType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WidthLevel">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value="W"/>
 *               &lt;enumeration value="w"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MinSeats" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaxSeats" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Note" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CraftTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CraftKind">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value=""/>
 *               &lt;enumeration value="S"/>
 *               &lt;enumeration value="M"/>
 *               &lt;enumeration value="L"/>
 *               &lt;enumeration value="m"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CraftInfoEntityType", propOrder = {
    "craftType",
    "widthLevel",
    "minSeats",
    "maxSeats",
    "note",
    "craftTypeName",
    "craftKind"
})
public class GetCraftInfoEntityType {

    @XmlElement(name = "CraftType", required = true)
    protected String craftType;
    @XmlElement(name = "WidthLevel", required = true)
    protected String widthLevel;
    @XmlElement(name = "MinSeats", required = true)
    protected String minSeats;
    @XmlElement(name = "MaxSeats", required = true)
    protected String maxSeats;
    @XmlElement(name = "Note", required = true)
    protected String note;
    @XmlElement(name = "CraftTypeName", required = true)
    protected String craftTypeName;
    @XmlElement(name = "CraftKind", required = true)
    protected String craftKind;

    /**
     * Gets the value of the craftType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCraftType() {
        return craftType;
    }

    /**
     * Sets the value of the craftType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCraftType(String value) {
        this.craftType = value;
    }

    /**
     * Gets the value of the widthLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidthLevel() {
        return widthLevel;
    }

    /**
     * Sets the value of the widthLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidthLevel(String value) {
        this.widthLevel = value;
    }

    /**
     * Gets the value of the minSeats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinSeats() {
        return minSeats;
    }

    /**
     * Sets the value of the minSeats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinSeats(String value) {
        this.minSeats = value;
    }

    /**
     * Gets the value of the maxSeats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxSeats() {
        return maxSeats;
    }

    /**
     * Sets the value of the maxSeats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxSeats(String value) {
        this.maxSeats = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the craftTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCraftTypeName() {
        return craftTypeName;
    }

    /**
     * Sets the value of the craftTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCraftTypeName(String value) {
        this.craftTypeName = value;
    }

    /**
     * Gets the value of the craftKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCraftKind() {
        return craftKind;
    }

    /**
     * Sets the value of the craftKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCraftKind(String value) {
        this.craftKind = value;
    }

}
