//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.07 at 06:06:50 PM CST 
//


package com.data.data.hmly.service.ctripflight.response.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetCraftInfosType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetCraftInfosType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RecordsCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CraftInfosList" type="{}CraftInfosListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetCraftInfosType", propOrder = {
    "recordsCount",
    "craftInfosList"
})
public class GetCraftInfosType {

    @XmlElement(name = "RecordsCount", required = true)
    protected String recordsCount;
    @XmlElement(name = "CraftInfosList", required = true)
    protected GetCraftInfosListType craftInfosList;

    /**
     * Gets the value of the recordsCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordsCount() {
        return recordsCount;
    }

    /**
     * Sets the value of the recordsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordsCount(String value) {
        this.recordsCount = value;
    }

    /**
     * Gets the value of the craftInfosList property.
     * 
     * @return
     *     possible object is
     *     {@link GetCraftInfosListType }
     *     
     */
    public GetCraftInfosListType getCraftInfosList() {
        return craftInfosList;
    }

    /**
     * Sets the value of the craftInfosList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetCraftInfosListType }
     *     
     */
    public void setCraftInfosList(GetCraftInfosListType value) {
        this.craftInfosList = value;
    }

}
