//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 03:36:59 PM CST 
//


package com.data.data.hmly.service.ctripflight.response.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Response_QNAME = new QName("", "Response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FlightResponseType }
     * 
     */
    public FlightResponseType createResponseType() {
        return new FlightResponseType();
    }

    /**
     * Create an instance of {@link DomesticFlightRouteType }
     * 
     */
    public DomesticFlightRouteType createDomesticFlightRouteType() {
        return new DomesticFlightRouteType();
    }

    /**
     * Create an instance of {@link CanPostCitiesCodeType }
     * 
     */
    public CanPostCitiesCodeType createCanPostCitiesCodeType() {
        return new CanPostCitiesCodeType();
    }

    /**
     * Create an instance of {@link InsuranceEntityType }
     * 
     */
    public InsuranceEntityType createInsuranceEntityType() {
        return new InsuranceEntityType();
    }

    /**
     * Create an instance of {@link FlightsListType }
     * 
     */
    public FlightsListType createFlightsListType() {
        return new FlightsListType();
    }

    /**
     * Create an instance of {@link FlightRoutesType }
     * 
     */
    public FlightRoutesType createFlightRoutesType() {
        return new FlightRoutesType();
    }

    /**
     * Create an instance of {@link FlightSearchResponseType }
     * 
     */
    public FlightSearchResponseType createFlightSearchResponseType() {
        return new FlightSearchResponseType();
    }

    /**
     * Create an instance of {@link PackageEntityType }
     * 
     */
    public PackageEntityType createPackageEntityType() {
        return new PackageEntityType();
    }

    /**
     * Create an instance of {@link DomesticFlightDataType }
     * 
     */
    public DomesticFlightDataType createDomesticFlightDataType() {
        return new DomesticFlightDataType();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlightResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Response")
    public JAXBElement<FlightResponseType> createResponse(FlightResponseType value) {
        return new JAXBElement<FlightResponseType>(_Response_QNAME, FlightResponseType.class, null, value);
    }

}
