//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 03:36:59 PM CST 
//


package com.data.data.hmly.service.ctripflight.response.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PackageEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackageEntityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CouponTypeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CouponTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CouponPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CouponNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackageEntityType", propOrder = {
    "couponTypeID",
    "couponTypeName",
    "couponPrice",
    "couponNum"
})
public class PackageEntityType {

    @XmlElement(name = "CouponTypeID", required = true)
    protected String couponTypeID;
    @XmlElement(name = "CouponTypeName", required = true)
    protected String couponTypeName;
    @XmlElement(name = "CouponPrice", required = true)
    protected String couponPrice;
    @XmlElement(name = "CouponNum", required = true)
    protected String couponNum;

    /**
     * Gets the value of the couponTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouponTypeID() {
        return couponTypeID;
    }

    /**
     * Sets the value of the couponTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouponTypeID(String value) {
        this.couponTypeID = value;
    }

    /**
     * Gets the value of the couponTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouponTypeName() {
        return couponTypeName;
    }

    /**
     * Sets the value of the couponTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouponTypeName(String value) {
        this.couponTypeName = value;
    }

    /**
     * Gets the value of the couponPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouponPrice() {
        return couponPrice;
    }

    /**
     * Sets the value of the couponPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouponPrice(String value) {
        this.couponPrice = value;
    }

    /**
     * Gets the value of the couponNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouponNum() {
        return couponNum;
    }

    /**
     * Sets the value of the couponNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouponNum(String value) {
        this.couponNum = value;
    }

}
