package com.data.data.hmly.service.entity;

// default package
// Generated 2015-10-14 17:07:39 by Hibernate Tools 4.0.0

import org.hibernate.annotations.Where;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * TbArea generated by hbm2java
 */
@Entity
@Table(name = "tb_area")
public class TbArea extends com.framework.hibernate.util.Entity implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -4875190604609069378L;
    @Id
    @GeneratedValue
    @Column(name = "id", unique = true, nullable = false)
    private Long id;
    @Column(name = "name", length = 200)
    private String name;
    @Column(name = "city_code", length = 20)
    private String cityCode;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "father", nullable = false, updatable = false)
    private TbArea father;
    @Column(name = "level")
    private Integer level;
    @Column(name = "full_path", length = 200)
    private String fullPath;
    @OneToMany(mappedBy = "father", fetch = FetchType.LAZY)
    private List<TbArea> childs;
    @Column(name = "pinyin", length = 200)
    private String pinyin;
    @Column(name = "recommended")
    private boolean recommended;

    @OneToOne(mappedBy = "tbArea", fetch = FetchType.LAZY, optional = true)
    private TbAreaExtend tbAreaExtend;

    @Transient
    private String proviceName;
    /**
     * 行程的城市天数
     */
    @Transient
    private Integer count;
    @Transient
    private transient Map<String, Object> extension = new HashMap<String, Object>();
    @OneToMany(fetch = FetchType.LAZY)
    @JoinColumn(name = "targetId", referencedColumnName = "id")
    @Where(clause = "targetType='CITY'")
    protected Set<LabelItem> labelItems;

    public TbArea() {
    }

    public TbArea(long id) {
        this.id = id;
    }

    public TbArea(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public TbArea(String name, TbArea father, Integer level, String fullPath) {
        this.name = name;
        this.father = father;
        this.level = level;
        this.fullPath = fullPath;
    }

    public TbArea(Long id, String name, String cityCode) {
        this.id = id;
        this.name = name;
        this.cityCode = cityCode;
    }

    public TbAreaExtend getTbAreaExtend() {
        return tbAreaExtend;
    }

    public void setTbAreaExtend(TbAreaExtend tbAreaExtend) {
        this.tbAreaExtend = tbAreaExtend;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public TbArea getFather() {
        return father;
    }

    public void setFather(TbArea father) {
        this.father = father;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public String getFullPath() {
        return fullPath;
    }

    public void setFullPath(String fullPath) {
        this.fullPath = fullPath;
    }

    public List<TbArea> getChilds() {
        return childs;
    }

    public void setChilds(List<TbArea> childs) {
        this.childs = childs;
    }

    public String getPinyin() {
        return pinyin;
    }

    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    public boolean isRecommended() {
        return recommended;
    }

    public void setRecommended(boolean recommended) {
        this.recommended = recommended;
    }

    public Map<String, Object> getExtension() {
        return extension;
    }

    public void setExtension(Map<String, Object> extension) {
        this.extension = extension;
    }

    public String getCityCode() {
        return cityCode;
    }

    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    public Set<LabelItem> getLabelItems() {
        return labelItems;
    }

    public void setLabelItems(Set<LabelItem> labelItems) {
        this.labelItems = labelItems;
    }

    public String getProviceName() {
        return proviceName;
    }

    public void setProviceName(String proviceName) {
        this.proviceName = proviceName;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }
}
