package com.data.data.hmly.service.common.entity;

import com.data.data.hmly.service.common.entity.enums.ProductSource;
import com.data.data.hmly.service.common.entity.enums.ProductStatus;
import com.data.data.hmly.service.common.entity.enums.ProductType;
import com.data.data.hmly.service.common.entity.enums.ShowStatus;
import com.data.data.hmly.service.entity.LabelItem;
import com.data.data.hmly.service.entity.SysUnit;
import com.data.data.hmly.service.entity.SysUser;
import org.hibernate.annotations.Where;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;
import java.util.List;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
@Inheritance(strategy = InheritanceType.JOINED)
//@Polymorphism(type=PolymorphismType.EXPLICIT)
public class Product extends com.framework.hibernate.util.Entity implements java.io.Serializable {
    /**
     *
     */
    private static final long serialVersionUID = -9215023448601457011L;
    @Id
    @GeneratedValue
    @Column(name = "id", unique = true, nullable = false)
    protected Long id;
    @Column(name = "name", length = 200)
    protected String name;
    @Column(name = "price", precision = 20)
    protected Float price;
    @Column(name = "status")
    @Enumerated(EnumType.STRING)
    protected ProductStatus status;
    @Column(name = "show_status")
    @Enumerated(EnumType.STRING)
    protected ShowStatus showStatus;
    @Column(name = "needConfirm")
    private Boolean needConfirm;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userid")
    protected SysUser user;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "companyUnitId")
    protected SysUnit companyUnit;
    @Column(name = "category")
    protected Long category;
    @Column(name = "proType", length = 10)
    @Enumerated(EnumType.STRING)
    protected ProductType proType;
    @Column(name = "cityId")
    protected Long cityId;
    @Column(name = "provienceId")
    protected Long provienceId;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parentId")
    protected Product parent;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "supplierId")
    protected SysUser supplier;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "topId")
    protected Product topProduct;
    @Column(name = "origin_id")
    protected Long originId;
    @OneToMany(mappedBy = "product")
    protected Set<Productimage> productimage;
    @OneToMany(fetch = FetchType.LAZY)
    @Where(clause = "targetType='HOTEL' or targetType ='LINE' or targetType ='PRODUCT' or targetType ='TRAFFIC'")
    @JoinColumn(name = "targetId", referencedColumnName = "id")
    protected Set<LabelItem> labelItems;
    @Column(name = "updateTime")
    protected Date updateTime;
    @Column(name = "createTime")
    protected Date createTime;

    @Column(name = "auditBy")
    private Long auditBy; // 审核人,
    @Column(name = "auditTime")
    private Date auditTime; // 审核时间,
    @Column(name = "auditReason")
    private String auditReason; // 审核原因,
    @Column(name = "tourPlaceType")


    @Transient
    protected transient String imgUrl;

    @Column(name = "source")
    @Enumerated(EnumType.STRING)
    protected ProductSource source;
    @Column(name = "sourceId")
    protected Long sourceId;

    @Column(name = "sourceStatus")
    private Boolean sourceStatus;

    @Column(name = "showOrder")
    private Integer showOrder;

    @Transient
    private String companyUnitName;

    @Transient
    private List<ProductStatus> productStatusList;

    @Transient
    private Integer imageTotalCount;

    @Transient
    private String sourceStr;

    public Product() {
    }

    public Product(Long id, String name, ProductType proType, SysUser user, SysUnit companyUnit) {
        this.id = id;
        this.name = name;
        this.proType = proType;
        this.user = user;
        this.companyUnit = companyUnit;
    }

    public Product(String name, Float price, ProductStatus status, SysUser user, Long category, ProductType proType, Long cityId) {
        this.name = name;
        this.price = price;
        this.status = status;
        this.user = user;
        this.category = category;
        this.proType = proType;
        this.cityId = cityId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public ProductStatus getStatus() {
        return status;
    }

    public ShowStatus getShowStatus() {
        return showStatus;
    }

    public void setShowStatus(ShowStatus showStatus) {
        this.showStatus = showStatus;
    }

    public void setStatus(ProductStatus status) {
        this.status = status;
    }

    public Boolean getNeedConfirm() {
        return needConfirm;
    }

    public void setNeedConfirm(Boolean needConfirm) {
        this.needConfirm = needConfirm;
    }

    public SysUser getUser() {
        return user;
    }

    public void setUser(SysUser user) {
        this.user = user;
    }

    public SysUnit getCompanyUnit() {
        return companyUnit;
    }

    public void setCompanyUnit(SysUnit companyUnit) {
        this.companyUnit = companyUnit;
    }

    public Long getCategory() {
        return category;
    }

    public void setCategory(Long category) {
        this.category = category;
    }

    public ProductType getProType() {
        return proType;
    }

    public void setProType(ProductType proType) {
        this.proType = proType;
    }

    public Long getCityId() {
        return cityId;
    }

    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    public Product getParent() {
        return parent;
    }

    public void setParent(Product parent) {
        this.parent = parent;
    }

    public SysUser getSupplier() {
        return supplier;
    }

    public void setSupplier(SysUser supplier) {
        this.supplier = supplier;
    }

    public Set<Productimage> getProductimage() {
        return productimage;
    }

    public void setProductimage(Set<Productimage> productimage) {
        this.productimage = productimage;
    }

    public Product getTopProduct() {
        return topProduct;
    }

    public void setTopProduct(Product topProduct) {
        this.topProduct = topProduct;
    }

    public Long getOriginId() {
        return originId;
    }

    public void setOriginId(Long originId) {
        this.originId = originId;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Set<LabelItem> getLabelItems() {
        return labelItems;
    }

    public void setLabelItems(Set<LabelItem> labelItems) {
        this.labelItems = labelItems;
    }

    public ProductSource getSource() {
        return source;
    }

    public void setSource(ProductSource source) {
        this.source = source;
    }

    public Long getSourceId() {
        return sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    public Long getProvienceId() {
        return provienceId;
    }

    public void setProvienceId(Long provienceId) {
        this.provienceId = provienceId;
    }


    public Long getAuditBy() {
        return auditBy;
    }

    public void setAuditBy(Long auditBy) {
        this.auditBy = auditBy;
    }

    public Date getAuditTime() {
        return auditTime;
    }

    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    public String getAuditReason() {
        return auditReason;
    }

    public void setAuditReason(String auditReason) {
        this.auditReason = auditReason;
    }

    public String getCompanyUnitName() {

        if (companyUnit != null) {
            return companyUnit.getName();
        }

        return companyUnitName;
    }

    public void setCompanyUnitName(String companyUnitName) {
        this.companyUnitName = companyUnitName;
    }

    public ProductType fmtProType(String type) {
        ProductType productType = null;
        if ("scenic".equals(type)) {
            productType = ProductType.scenic;
        }
        if ("line".equals(type)) {
            productType = ProductType.line;
        }
        if ("delicacy".equals(type)) {
            productType = ProductType.delicacy;
        }
        if ("flight".equals(type)) {
            productType = ProductType.flight;
        }
        if ("hotel".equals(type)) {
            productType = ProductType.hotel;
        }
        if ("impression".equals(type)) {
            productType = ProductType.impression;
        }
        if ("plan".equals(type)) {
            productType = ProductType.plan;
        }
        if ("recplan".equals(type)) {
            productType = ProductType.recplan;
        }
        if ("restaurant".equals(type)) {
            productType = ProductType.restaurant;
        }
        if ("train".equals(type)) {
            productType = ProductType.train;
        }
        return productType;
    }

    public Boolean getSourceStatus() {
        return sourceStatus;
    }

    public void setSourceStatus(Boolean sourceStatus) {
        this.sourceStatus = sourceStatus;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof Product) {
            Product p = (Product) obj;
            return this.id.equals(p.getId());
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return super.hashCode();
    }

    public List<ProductStatus> getProductStatusList() {
        return productStatusList;
    }

    public void setProductStatusList(List<ProductStatus> productStatusList) {
        this.productStatusList = productStatusList;
    }

    public Integer getShowOrder() {
        return showOrder;
    }

    public void setShowOrder(Integer showOrder) {
        this.showOrder = showOrder;
    }

    public Integer getImageTotalCount() {
        return imageTotalCount;
    }

    public void setImageTotalCount(Integer imageTotalCount) {
        this.imageTotalCount = imageTotalCount;
    }

    public String getSourceStr() {
        return sourceStr;
    }

    public void setSourceStr(String sourceStr) {
        this.sourceStr = sourceStr;
    }
}
