package com.zuipin.pojo;

// Generated 2015-2-5 16:57:27 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Express generated by hbm2java
 */
@Entity
@Table(name = "express")
public class Express implements java.io.Serializable {
	
	private Long	id;
	private String	code;
	private String	name;
	
	public Express() {
	}
	
	public Express(String code, String name) {
		this.code = code;
		this.name = name;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}
	
	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "CODE", length = 200)
	public String getCode() {
		return this.code;
	}
	
	public void setCode(String code) {
		this.code = code;
	}
	
	@Column(name = "NAME", length = 500)
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
}
