<xml>
<ToUserName><![CDATA[#toUser]]></ToUserName>
<FromUserName><![CDATA[#WxName]]></FromUserName>
<CreateTime>#createTime</CreateTime>
<MsgType><![CDATA[voice]]></MsgType>
<Voice>
<MediaId><![CDATA[#mediaId]]></MediaId>
</Voice>
</xml>