<xml>
<ToUserName><![CDATA[#toUser]]></ToUserName>
<FromUserName><![CDATA[#WxName]]></FromUserName>
<CreateTime>#createTime</CreateTime>
<MsgType><![CDATA[news]]></MsgType>
<ArticleCount>#count</ArticleCount>
<Articles>
#items
</Articles>
</xml> 