//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 05:35:30 PM CST 
//


package com.data.data.hmly.service.ctripticket.entity;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.util.Date;

//@Entity
//@Table(name = "ctrip_ticket_price_daily")
public class CtripTicketPriceDaily extends com.framework.hibernate.util.Entity {
	private static final long serialVersionUID = -4721924498569505170L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", length = 20)
	private Long	id;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
    private Date 	date;
	@Column(name = "price", length = 20, precision=2)
    private Double price;
	@Column(name = "marketPrice", length = 20, precision=2)
    private Double marketPrice;
	@Column(name = "costPrice", length = 20, precision=2)
    private Double costPrice;
	@Column(name = "minQuantity", length = 11)
    private Integer minQuantity;
	@Column(name = "maxQuantity", length = 11)
    private Integer maxQuantity;
	@Column(name = "inventoryNum", length = 11)
    private Integer inventoryNum;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	private Date createTime;
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "updateTime", length = 19)
//	private Date updateTime;
//	@Column(name = "rowStatus")
//	@Enumerated(EnumType.STRING)
//	private RowStatus rowStatus;
	@Column(name = "ticketId", length = 11)
    private Integer ticketId;
	@Column(name = "ticketResourceId", length = 11)
    private Integer ticketResourceId;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	public Double getPrice() {
		return price;
	}
	public void setPrice(Double price) {
		this.price = price;
	}
	public Double getMarketPrice() {
		return marketPrice;
	}
	public void setMarketPrice(Double marketPrice) {
		this.marketPrice = marketPrice;
	}
	public Double getCostPrice() {
		return costPrice;
	}
	public void setCostPrice(Double costPrice) {
		this.costPrice = costPrice;
	}
	public Integer getMinQuantity() {
		return minQuantity;
	}
	public void setMinQuantity(Integer minQuantity) {
		this.minQuantity = minQuantity;
	}
	public Integer getMaxQuantity() {
		return maxQuantity;
	}
	public void setMaxQuantity(Integer maxQuantity) {
		this.maxQuantity = maxQuantity;
	}
	public Integer getInventoryNum() {
		return inventoryNum;
	}
	public void setInventoryNum(Integer inventoryNum) {
		this.inventoryNum = inventoryNum;
	}
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public Integer getTicketId() {
		return ticketId;
	}
	public void setTicketId(Integer ticketId) {
		this.ticketId = ticketId;
	}
	public Integer getTicketResourceId() {
		return ticketResourceId;
	}
	public void setTicketResourceId(Integer ticketResourceId) {
		this.ticketResourceId = ticketResourceId;
	}


}
