package com.data.data.hmly.service.line.entity;

// Generated 2015-10-22 10:47:22 by Hibernate Tools 3.4.0.CR1

import com.data.data.hmly.service.common.entity.enums.ProductType;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Linedaysplan generated by hbm2java
 */
@Entity
@Table(name = "linedaysproductprice")
public class LinedaysProductPrice extends com.framework.hibernate.util.Entity implements java.io.Serializable, Cloneable {
	private static final long serialVersionUID = 5566678345524151611L;
	private Long id;
	private Long lineId;
	private Linedays linedays;
    private ProductType productType;
    private Long productId;
    private String productName;
    private Long priceId;
    private String priceName;
	private Long userId;
	private Date createTime;
	private Long foodId;
    private Integer showOrder;
	private Long scenicInfoId;
    // 页面字段
	private Long linedaysId;

	public LinedaysProductPrice() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "lineId")
	public Long getLineId() {
		return this.lineId;
	}

	public void setLineId(Long lineId) {
		this.lineId = lineId;
	}

	@ManyToOne
	@JoinColumn(name = "linedaysId")
	public Linedays getLinedays() {
		return linedays;
	}

	public void setLinedays(Linedays linedays) {
		this.linedays = linedays;
	}

	@Column(name = "showOrder")
	public Integer getShowOrder() {
		return this.showOrder;
	}

	public void setShowOrder(Integer showOrder) {
		this.showOrder = showOrder;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "foodId")
	public Long getFoodId() {
		return foodId;
	}

	public void setFoodId(Long foodId) {
		this.foodId = foodId;
	}

    @Column(name = "productType")
    @Enumerated(EnumType.STRING)
    public ProductType getProductType() {
        return productType;
    }

    public void setProductType(ProductType productType) {
        this.productType = productType;
    }

    @Column(name = "productId")
    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    @Column(name = "productName")
    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    @Column(name = "priceId")
    public Long getPriceId() {
        return priceId;
    }

    public void setPriceId(Long priceId) {
        this.priceId = priceId;
    }

    @Column(name = "priceName")
    public String getPriceName() {
        return priceName;
    }

    public void setPriceName(String priceName) {
        this.priceName = priceName;
    }

	@Column(name = "scenicInfoId")
	public Long getScenicInfoId() {
		return scenicInfoId;
	}

	public void setScenicInfoId(Long scenicInfoId) {
		this.scenicInfoId = scenicInfoId;
	}

	@Transient
    public Long getLinedaysId() {
        return linedaysId;
    }

    public void setLinedaysId(Long linedaysId) {
        this.linedaysId = linedaysId;
    }
}
