package com.data.data.hmly.service.line.entity;

// Generated 2015-10-19 21:17:00 by Hibernate Tools 4.0.0

import com.data.data.hmly.service.common.entity.enums.ProductType;
import com.data.data.hmly.service.common.entity.interfaces.ProductPrice;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import java.util.Date;

/**
 * Linetypepricedate generated by hbm2java
 */
@Entity
@Table(name = "linetypepricedate")
public class Linetypepricedate extends com.framework.hibernate.util.Entity implements java.io.Serializable, ProductPrice, Cloneable {

	private static final long serialVersionUID = -2651158156745215913L;
	private Long id;
	private Linetypeprice linetypeprice;
	private Long lineId;
	private Date day;
	private Float discountPrice;
	private Float marketPrice;
	private Float childPrice;
	private Float childMarketPrice;
	private Float oasiaHotel;
	private Long userId;
	private Date createTime;
	private Long levelType;
	private Integer inventory;


	/**
	 * 佣金
	 */
	private Float rebate;
	private Float childRebate;

	public Linetypepricedate() {
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "linetypepriceId")
	public Linetypeprice getLinetypeprice() {
		return linetypeprice;
	}

	public void setLinetypeprice(Linetypeprice linetypeprice) {
		this.linetypeprice = linetypeprice;
	}

	@Column(name = "lineId")
	public Long getLineId() {
		return lineId;
	}

	public void setLineId(Long lineId) {
		this.lineId = lineId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "day", length = 19)
	public Date getDay() {
		return day;
	}

	public void setDay(Date day) {
		this.day = day;
	}

	@Column(name = "discountPrice", precision = 20)
	public Float getDiscountPrice() {
		return discountPrice;
	}

	public void setDiscountPrice(Float discountPrice) {
		this.discountPrice = discountPrice;
	}

	@Column(name = "childPrice", precision = 20)
	public Float getChildPrice() {
		return childPrice;
	}

	public void setChildPrice(Float childPrice) {
		this.childPrice = childPrice;
	}


	@Column(name = "oasia_hotel", precision = 20)
	public Float getOasiaHotel() {
		return oasiaHotel;
	}

	public void setOasiaHotel(Float oasiaHotel) {
		this.oasiaHotel = oasiaHotel;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "levelType")
	public Long getLevelType() {
		return levelType;
	}

	public void setLevelType(Long levelType) {
		this.levelType = levelType;
	}

	@Column(name = "rebate", precision = 20)
	public Float getRebate() {
		return rebate;
	}

	public void setRebate(Float rebate) {
		this.rebate = rebate;
	}

	@Column(name = "childRebate", precision = 20)
	public Float getChildRebate() {
		return childRebate;
	}

	public void setChildRebate(Float childRebate) {
		this.childRebate = childRebate;
	}

	@Column(name = "marketPrice", precision = 20)
	public Float getMarketPrice() {
		return marketPrice;
	}

	public void setMarketPrice(Float marketPrice) {
		this.marketPrice = marketPrice;
	}
	@Column(name = "childMarketPrice", precision = 20)
	public Float getChildMarketPrice() {
		return childMarketPrice;
	}

	public void setChildMarketPrice(Float childMarketPrice) {
		this.childMarketPrice = childMarketPrice;
	}

	@Override
	@Transient
	public Long getProductId() {
		return lineId;
	}

	@Override
	@Transient
	public Long getPriceId() {
		return id;
	}

	@Override
	@Transient
	public String getName() {
		return linetypeprice.getLine().getName();
	}

	@Override
	@Transient
	public Float getPrice() {
		return discountPrice;
	}

	@Override
	@Transient
	public Date getDate() {
		return day;
	}

	@Override
	@Transient
	public ProductType getProductType() {
		return linetypeprice.getLine().getProType();
	}

	@Override
	public Linetypepricedate clone() throws CloneNotSupportedException {
		return (Linetypepricedate) super.clone();
	}

	public Integer getInventory() {
		return inventory;
	}

	public void setInventory(Integer inventory) {
		this.inventory = inventory;
	}


}
