package com.data.data.hmly.service.line.entity;

// Generated 2015-10-15 11:48:07 by Hibernate Tools 4.0.0


import com.data.data.hmly.service.common.entity.Product;
import com.data.data.hmly.service.line.entity.enums.Buypay;
import com.data.data.hmly.service.line.entity.enums.CombineType;
import com.data.data.hmly.service.line.entity.enums.LineConfirmAndPayType;
import com.data.data.hmly.service.line.entity.enums.LineStatus;
import com.data.data.hmly.service.line.entity.enums.PaySet;
import com.data.data.hmly.service.line.entity.enums.ProductAttr;
import com.data.data.hmly.service.line.entity.enums.ScoreExchange;
import com.data.data.hmly.service.line.entity.enums.TourPlaceType;
import org.apache.commons.lang.StringUtils;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import java.util.Date;
import java.util.List;
import java.util.Set;

/**
 * Line generated by hbm2java
 */
@Entity
@Table(name = "line")
@PrimaryKeyJoinColumn(name = "productId")
public class Line extends Product implements java.io.Serializable, Cloneable {

	private static final long serialVersionUID = -3429057633149659474L;
	@Column(name = "lineType", length = 6)
	private String lineType;
	@Enumerated(EnumType.STRING)
	@Column(name = "productAttr", length = 11)
	private ProductAttr productAttr;
	@Column(name = "appendTitle", length = 50)
	private String appendTitle;
	@Column(name = "startCityId")
	private Long startCityId;
	@Column(name = "arriveCityId")
	private Long arriveCityId;
	@Column(name = "preOrderDay")
	private Integer preOrderDay;
	@Column(name = "suggestOrderHour")
	private Integer suggestOrderHour;
	@Column(name = "validOrderDay")
	private Integer validOrderDay;
	@Column(name = "playDay")
	private Integer playDay;
	@Column(name = "buypay", length = 11)
	@Enumerated(EnumType.STRING)
	private Buypay buypay;
	@Column(name = "goWay", length = 6)
	private String goWay;
	@Column(name = "backWay", length = 6)
	private String backWay;
	@Column(name = "lineImageUrl", length = 500)
	private String lineImageUrl;
	@Column(name = "showOrder")
	private Integer showOrder;
	@Column(name = "paySet", length = 7)
	@Enumerated(EnumType.STRING)
	private PaySet paySet;
	@Column(name = "earnestMoney", precision = 20)
	private Float earnestMoney;
	@Column(name = "confirmAndPay")
    @Enumerated(EnumType.STRING)
	private LineConfirmAndPayType confirmAndPay;
	@Column(name = "lineStatus")
	@Enumerated(EnumType.STRING)
	private LineStatus lineStatus;
	@Column(name = "userId")
	private Long userId;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	private Date createTime;
	@Column(name = "migImg", length = 500)
	private String migImg;
	@Column(name = "middleImg", length = 500)
	private String middleImg;
	@Column(name = "smallImg", length = 500)
	private String smallImg;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	private Date updateTime;
	@OneToOne(mappedBy = "line", fetch = FetchType.LAZY)
	private Linestatistic linestatistic;
	@Column(name = "productNo", length = 20)
	private String productNo;
	@Column(name = "wayDesc", length = 500)
	private String wayDesc;
	@Column(name = "productRemark", length = 500)
	private String productRemark;
	@Column(name = "scoreExchange")
	@Enumerated(EnumType.STRING)
	private ScoreExchange scoreExchange;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "line")
	private Set<Lineacrosscitys> lineacrosscitys;
	@Column(name = "short_desc")
	private String shortDesc;
	@Column(name = "comment_sum")
	private Integer commentSum;
	@Column(name = "order_sum")
	private Integer orderSum;
	@Column(name = "collect_sum")
	private Integer collectSum;
    @Column(name = "auditBy")
	private Long auditBy; // 审核人,
    @Column(name = "auditTime")
	private Date auditTime; // 审核时间,
    @Column(name = "auditReason")
	private String auditReason; // 审核原因,
	@Column(name = "tourPlaceType")
	@Enumerated(EnumType.STRING)
	private TourPlaceType tourPlaceType;		// 发团地点类型：start-出发地成团；dest-目的地成团
    @Column(name = "satisfaction")
    private Integer satisfaction;
	@Column(name = "combineType")
	@Enumerated(EnumType.STRING)
	private CombineType combineType;

	// 页面字段
	@Transient
	private String scoreExchangeParticipation;
	@Transient
	private String paySetNoClose;
	@Transient
	private String clickNumLt10;
	@Transient
	private String orderNumEq0;
	@Transient
	private Boolean agentFlag;
	@Transient
	private String agentLine;
	@Transient
	private String siteurl;
	@Transient
	private String keyword;
	@Transient
	private String sourceStr;
	@Transient
	private String companyPhone;    //供应商手机
	@Transient
	private String companyQQ;       //供应商QQ
	@Transient
	private String suplierName;       //供应商名称
    @Transient
    private String minPrice; // 线路最近1个月最低价格, 用户前台展示
	@Transient
	private String cover;
    @Transient
    private String coverDesc;
	@Transient
	private Long startCountryId;
	@Transient
	private Long startProvinceId;
	@Transient
	private Long arriveCountryId;
	@Transient
	private Long arriveProvinceId;

    @OneToMany(mappedBy = "line")
    private List<LineInsurance> lineInsuranceList;

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id")
	private Lineexplain lineexplain;
	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "lineId")
	private Set<Linetypeprice> linetypeprices;
	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "lineId")
	private Set<Lineplaytitle> lineplaytitles;

	public Line() {
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public String getLineType() {
		return lineType;
	}

	public void setLineType(String lineType) {
		this.lineType = lineType;
	}

	public ProductAttr getProductAttr() {
		return productAttr;
	}

	public void setProductAttr(ProductAttr productAttr) {
		this.productAttr = productAttr;
	}

	public String getAppendTitle() {
		return appendTitle;
	}

	public void setAppendTitle(String appendTitle) {
		this.appendTitle = appendTitle;
	}

	public Long getStartCityId() {
		return startCityId;
	}

	public void setStartCityId(Long startCityId) {
		this.startCityId = startCityId;
	}

	public Integer getPreOrderDay() {
		return preOrderDay;
	}

	public void setPreOrderDay(Integer preOrderDay) {
		this.preOrderDay = preOrderDay;
	}

	public Integer getSuggestOrderHour() {
		return suggestOrderHour;
	}

	public void setSuggestOrderHour(Integer suggestOrderHour) {
		this.suggestOrderHour = suggestOrderHour;
	}

	public Integer getValidOrderDay() {
		return validOrderDay;
	}

	public void setValidOrderDay(Integer validOrderDay) {
		this.validOrderDay = validOrderDay;
	}

	public Integer getPlayDay() {
		return playDay;
	}

	public void setPlayDay(Integer playDay) {
		this.playDay = playDay;
	}

	public Buypay getBuypay() {
		return buypay;
	}

	public void setBuypay(Buypay buypay) {
		this.buypay = buypay;
	}

	public String getGoWay() {
		return goWay;
	}

	public void setGoWay(String goWay) {
		this.goWay = goWay;
	}

	public String getBackWay() {
		return backWay;
	}

	public void setBackWay(String backWay) {
		this.backWay = backWay;
	}

	public String getLineImageUrl() {
		return lineImageUrl;
	}

	public void setLineImageUrl(String lineImageUrl) {
		this.lineImageUrl = lineImageUrl;
	}

	public Integer getShowOrder() {
		return showOrder;
	}

	public void setShowOrder(Integer showOrder) {
		this.showOrder = showOrder;
	}

	public PaySet getPaySet() {
		return paySet;
	}

	public void setPaySet(PaySet paySet) {
		this.paySet = paySet;
	}

	public Float getEarnestMoney() {
		return earnestMoney;
	}

	public void setEarnestMoney(Float earnestMoney) {
		this.earnestMoney = earnestMoney;
	}

    public LineConfirmAndPayType getConfirmAndPay() {
        return confirmAndPay;
    }

    public void setConfirmAndPay(LineConfirmAndPayType confirmAndPay) {
        this.confirmAndPay = confirmAndPay;
    }

    public LineStatus getLineStatus() {
		return lineStatus;
	}

	public void setLineStatus(LineStatus lineStatus) {
		this.lineStatus = lineStatus;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getMigImg() {
		return migImg;
	}

	public void setMigImg(String migImg) {
		this.migImg = migImg;
	}

	public String getMiddleImg() {
		return middleImg;
	}

	public void setMiddleImg(String middleImg) {
		this.middleImg = middleImg;
	}

	public String getSmallImg() {
		return smallImg;
	}

	public void setSmallImg(String smallImg) {
		this.smallImg = smallImg;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Linestatistic getLinestatistic() {
		return linestatistic;
	}

	public void setLinestatistic(Linestatistic linestatistic) {
		this.linestatistic = linestatistic;
	}

	public String getProductNo() {
		return productNo;
	}

	public void setProductNo(String productNo) {
		this.productNo = productNo;
	}

	public String getWayDesc() {
		return wayDesc;
	}

	public void setWayDesc(String wayDesc) {
		this.wayDesc = wayDesc;
	}

	public String getProductRemark() {
		return productRemark;
	}

	public void setProductRemark(String productRemark) {
		this.productRemark = productRemark;
	}

	public ScoreExchange getScoreExchange() {
		return scoreExchange;
	}

	public void setScoreExchange(ScoreExchange scoreExchange) {
		this.scoreExchange = scoreExchange;
	}

	public String getScoreExchangeParticipation() {
		return scoreExchangeParticipation;
	}

	public void setScoreExchangeParticipation(String scoreExchangeParticipation) {
		this.scoreExchangeParticipation = scoreExchangeParticipation;
	}

	public String getPaySetNoClose() {
		return paySetNoClose;
	}

	public void setPaySetNoClose(String paySetNoClose) {
		this.paySetNoClose = paySetNoClose;
	}

	public String getClickNumLt10() {
		return clickNumLt10;
	}

	public void setClickNumLt10(String clickNumLt10) {
		this.clickNumLt10 = clickNumLt10;
	}

	public String getOrderNumEq0() {
		return orderNumEq0;
	}

	public void setOrderNumEq0(String orderNumEq0) {
		this.orderNumEq0 = orderNumEq0;
	}

    public String getMinPrice() {
        return minPrice;
    }

    public void setMinPrice(String minPrice) {
        this.minPrice = minPrice;
    }

    public Lineexplain getLineexplain() {
		return lineexplain;
	}

	public void setLineexplain(Lineexplain lineexplain) {
		this.lineexplain = lineexplain;
	}

	public Set<Linetypeprice> getLinetypeprices() {
		return linetypeprices;
	}

	public void setLinetypeprices(Set<Linetypeprice> linetypeprices) {
		this.linetypeprices = linetypeprices;
	}

	public Set<Lineplaytitle> getLineplaytitles() {
		return lineplaytitles;
	}

	public void setLineplaytitles(Set<Lineplaytitle> lineplaytitles) {
		this.lineplaytitles = lineplaytitles;
	}

	public Set<Lineacrosscitys> getLineacrosscitys() {
		return lineacrosscitys;
	}

	public void setLineacrosscitys(Set<Lineacrosscitys> lineacrosscitys) {
		this.lineacrosscitys = lineacrosscitys;
	}

	public Boolean getAgentFlag() {
		agentFlag = false;
		if (topProduct != null) {
			agentFlag = id != topProduct.getId();
		}
		return agentFlag;
	}



	public String getAgentLine() {
		return agentLine;
	}

	public void setAgentLine(String agentLine) {
		this.agentLine = agentLine;
	}

	public String getSiteurl() {
		if (companyUnit != null && companyUnit.getSysSite() != null) {
			siteurl = companyUnit.getSysSite().getSiteurl();
		}
		return siteurl;
	}

	public void setSiteurl(String siteurl) {
		this.siteurl = siteurl;
	}

	public String getCompanyPhone() {

		if (user != null) {
			return user.getMobile();
		}
		return companyPhone;
	}


	public String getCompanyQQ() {
		if (user != null) {
			return user.getQqNo();
		}
		return companyQQ;
	}


	public String getSuplierName() {
		return suplierName;
	}

	public void setSuplierName(String suplierName) {
		this.suplierName = suplierName;
	}

	public String getSourceStr() {
		return sourceStr;
	}

	public void setSourceStr(String sourceStr) {
		this.sourceStr = sourceStr;
	}


	public Long getArriveCityId() {
		return arriveCityId;
	}

	public void setArriveCityId(Long arriveCityId) {
		this.arriveCityId = arriveCityId;
	}

	public String getShortDesc() {
		return shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	public Integer getCommentSum() {
		return commentSum;
	}

	public void setCommentSum(Integer commentSum) {
		this.commentSum = commentSum;
	}

	public Integer getOrderSum() {
		return orderSum;
	}

	public void setOrderSum(Integer orderSum) {
		this.orderSum = orderSum;
	}

	public Integer getCollectSum() {
		return collectSum;
	}

	public void setCollectSum(Integer collectSum) {
		this.collectSum = collectSum;
	}

	public String getCover() {
		return cover;
	}

	public void setCover(String cover) {
		this.cover = cover;
	}

    public String getCoverDesc() {
        return coverDesc;
    }

    public void setCoverDesc(String coverDesc) {
        this.coverDesc = coverDesc;
    }

    public List<LineInsurance> getLineInsuranceList() {
        return lineInsuranceList;
    }

    public void setLineInsuranceList(List<LineInsurance> lineInsuranceList) {
        this.lineInsuranceList = lineInsuranceList;
    }

    public String getGoWayString() {
		if (StringUtils.isNotBlank(this.goWay)) {
			switch (this.goWay) {
				case "plane": return "飞机";
				case "car": return "汽车";
				case "train": return "火车";
				case "bus": return "巴士";
				case "ship": return "船";
				case "dongche": return "动车";
				case "gaotie": return "高铁";
				default: return "";
			}
		}
		return "";
	}
	public String getBackWayString() {
		if (StringUtils.isNotBlank(this.backWay)) {
			switch (this.backWay) {
				case "plane":
					return "飞机";
				case "car":
					return "汽车";
				case "train":
					return "火车";
				case "bus":
					return "巴士";
				case "ship":
					return "船";
				case "dongche":
					return "动车";
				case "gaotie":
					return "高铁";
				default:
					return "";
			}
		}
		return "";
	}

    public Long getAuditBy() {
        return auditBy;
    }

    public void setAuditBy(Long auditBy) {
        this.auditBy = auditBy;
    }

    public Date getAuditTime() {
        return auditTime;
    }

    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    public String getAuditReason() {
        return auditReason;
    }

    public void setAuditReason(String auditReason) {
        this.auditReason = auditReason;
    }

	@Override
	public Line clone() throws CloneNotSupportedException {
		return (Line) super.clone();
	}

	public TourPlaceType getTourPlaceType() {
		return tourPlaceType;
	}

	public void setTourPlaceType(TourPlaceType tourPlaceType) {
		this.tourPlaceType = tourPlaceType;
	}

    public Integer getSatisfaction() {
        return satisfaction;
    }

    public void setSatisfaction(Integer satisfaction) {
        this.satisfaction = satisfaction;
    }

    public String getKeyword() {
		return keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public Long getStartCountryId() {
		return startCountryId;
	}

	public void setStartCountryId(Long startCountryId) {
		this.startCountryId = startCountryId;
	}

	public Long getStartProvinceId() {
		return startProvinceId;
	}

	public void setStartProvinceId(Long startProvinceId) {
		this.startProvinceId = startProvinceId;
	}

	public Long getArriveCountryId() {
		return arriveCountryId;
	}

	public void setArriveCountryId(Long arriveCountryId) {
		this.arriveCountryId = arriveCountryId;
	}

	public Long getArriveProvinceId() {
		return arriveProvinceId;
	}

	public void setArriveProvinceId(Long arriveProvinceId) {
		this.arriveProvinceId = arriveProvinceId;
	}

	public CombineType getCombineType() {
		return combineType;
	}

	public void setCombineType(CombineType combineType) {
		this.combineType = combineType;
	}
}
