package com.data.data.hmly.service.other.entity;

// Generated 2015-12-22 10:51:28 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.data.data.hmly.service.common.entity.enums.ProductType;

/**
 * OtherVisitHistory generated by hbm2java
 */
@Entity
@Table(name = "other_visit_history")
public class OtherVisitHistory extends com.framework.hibernate.util.Entity {

	private static final long serialVersionUID = -3417503438782700066L;
	private Long id;
	private ProductType resType;
	private String title;
	private String introduction;
	private String imgPath;
	private String path;
	private String resObject;
	private Long resObjectId;
	private String visitIp;
	private String cookieId;
	private Long userId;
	private Date createTime;
	private Boolean deleteFlag;
	
	// 页面字段
	private Float price;

	public OtherVisitHistory() {
	}

	public OtherVisitHistory(Long id, String title, String introduction,
			String imgPath, Long resObjectId, Date createTime) {
		this.id = id;
		this.title = title;
		this.introduction = introduction;
		this.imgPath = imgPath;
		this.resObjectId = resObjectId;
		this.createTime = createTime;
	}

	public OtherVisitHistory(Long id, String title, String introduction,
			String imgPath, Long resObjectId, Date createTime, Float price) {
		this.id = id;
		this.title = title;
		this.introduction = introduction;
		this.imgPath = imgPath;
		this.resObjectId = resObjectId;
		this.createTime = createTime;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "resType", nullable = false)
	@Enumerated(EnumType.STRING)
	public ProductType getResType() {
		return this.resType;
	}

	public void setResType(ProductType resType) {
		this.resType = resType;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "introduction")
	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	@Column(name = "imgPath")
	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	@Column(name = "path")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "resObject")
	public String getResObject() {
		return this.resObject;
	}

	public void setResObject(String resObject) {
		this.resObject = resObject;
	}

	@Column(name = "resObjectId", nullable = false)
	public Long getResObjectId() {
		return this.resObjectId;
	}

	public void setResObjectId(Long resObjectId) {
		this.resObjectId = resObjectId;
	}

	@Column(name = "visitIp", length = 100)
	public String getVisitIp() {
		return this.visitIp;
	}

	public void setVisitIp(String visitIp) {
		this.visitIp = visitIp;
	}

	@Column(name = "cookieId", nullable = false, length = 100)
	public String getCookieId() {
		return this.cookieId;
	}

	public void setCookieId(String cookieId) {
		this.cookieId = cookieId;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "deleteFlag", nullable = false)
	public Boolean getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Transient
	public Float getPrice() {
		return price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}
	

}
