//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 10:55:20 AM CST 
//


package com.data.data.hmly.service.ctripflight.request.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestBodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestBodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FlightSearchRequest" type="{}FlightSearchRequestType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestBodyType", propOrder = {
    "flightSearchRequest"
})
public class FlightSearchRequestBodyType {

    @XmlElement(name = "FlightSearchRequest", required = true)
    protected FlightSearchRequestType flightSearchRequest;

    /**
     * Gets the value of the flightSearchRequest property.
     * 
     * @return
     *     possible object is
     *     {@link FlightSearchRequest }
     *     
     */
    public FlightSearchRequestType getFlightSearchRequest() {
        return flightSearchRequest;
    }

    /**
     * Sets the value of the flightSearchRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightSearchRequest }
     *     
     */
    public void setFlightSearchRequest(FlightSearchRequestType value) {
        this.flightSearchRequest = value;
    }

}
