//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.05 at 05:26:36 PM CST 
//


package com.data.data.hmly.service.ctripflight.request.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{}HeaderType"/>
 *         &lt;element name="FltCancelOrderRequest" type="{}FltCancelOrderRequestType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestType", propOrder = {
    "header",
    "fltCancelOrderRequest"
})
@XmlRootElement(name="Request")
public class FltCancelRequestType {

    @XmlElement(name = "Header", required = true)
    protected FltCancelOrderHeaderType header;
    @XmlElement(name = "FltCancelOrderRequest", required = true)
    protected FltCancelOrderRequestType fltCancelOrderRequest;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link FltCancelOrderHeaderType }
     *     
     */
    public FltCancelOrderHeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltCancelOrderHeaderType }
     *     
     */
    public void setHeader(FltCancelOrderHeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the fltCancelOrderRequest property.
     * 
     * @return
     *     possible object is
     *     {@link FltCancelOrderRequestType }
     *     
     */
    public FltCancelOrderRequestType getFltCancelOrderRequest() {
        return fltCancelOrderRequest;
    }

    /**
     * Sets the value of the fltCancelOrderRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltCancelOrderRequestType }
     *     
     */
    public void setFltCancelOrderRequest(FltCancelOrderRequestType value) {
        this.fltCancelOrderRequest = value;
    }

}
