//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.05 at 01:48:07 PM CST 
//


package com.data.data.hmly.service.ctripflight.request.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{}HeaderType"/>
 *         &lt;element name="FltSaveOrderRequest" type="{}FltSaveOrderRequestType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestType", propOrder = {
    "header",
    "fltSaveOrderRequest"
})
@XmlRootElement(name="Request")
public class FltOrderRequestType {
	
    @XmlElement(name = "Header", required = true)
    protected FltOrderHeaderType header;
    @XmlElement(name = "FltSaveOrderRequest", required = true)
    protected FltSaveOrderRequestType fltSaveOrderRequest;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link FltOrderHeaderType }
     *     
     */
    public FltOrderHeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltOrderHeaderType }
     *     
     */
    public void setHeader(FltOrderHeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the fltSaveOrderRequest property.
     * 
     * @return
     *     possible object is
     *     {@link FltSaveOrderRequestType }
     *     
     */
    public FltSaveOrderRequestType getFltSaveOrderRequest() {
        return fltSaveOrderRequest;
    }

    /**
     * Sets the value of the fltSaveOrderRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltSaveOrderRequestType }
     *     
     */
    public void setFltSaveOrderRequest(FltSaveOrderRequestType value) {
        this.fltSaveOrderRequest = value;
    }

}
