//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.05 at 01:48:07 PM CST 
//


package com.data.data.hmly.service.ctripflight.request.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FltSaveOrderRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FltSaveOrderRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProcessDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FlightInfoList" type="{}FlightInfoListType"/>
 *         &lt;element name="PassengerList" type="{}PassengerListType"/>
 *         &lt;element name="ContactInfo" type="{}ContactInfoType"/>
 *         &lt;element name="DeliverInfo" type="{}DeliverInfoType"/>
 *         &lt;element name="PayInfo" type="{}PayInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FltSaveOrderRequestType", propOrder = {
    "uid",
    "orderType",
    "amount",
    "processDesc",
    "flightInfoList",
    "passengerList",
    "contactInfo",
    "deliverInfo",
    "payInfo"
})
public class FltSaveOrderRequestType {

    @XmlElement(name = "UID", required = true)
    protected String uid;
    @XmlElement(name = "OrderType", required = true)
    protected String orderType;
    @XmlElement(name = "Amount", required = true)
    protected String amount;
    @XmlElement(name = "ProcessDesc", required = true)
    protected String processDesc;
    @XmlElement(name = "FlightInfoList", required = true)
    protected FltOrderFlightInfoListType flightInfoList;
    @XmlElement(name = "PassengerList", required = true)
    protected FltOrderPassengerListType passengerList;
    @XmlElement(name = "ContactInfo", required = true)
    protected FltOrderContactInfoType contactInfo;
    @XmlElement(name = "DeliverInfo", required = true)
    protected FltOrderDeliverInfoType deliverInfo;
    @XmlElement(name = "PayInfo", required = true)
    protected FltOrderPayInfoType payInfo;

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUID() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUID(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the orderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderType(String value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the processDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessDesc() {
        return processDesc;
    }

    /**
     * Sets the value of the processDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessDesc(String value) {
        this.processDesc = value;
    }

    /**
     * Gets the value of the flightInfoList property.
     * 
     * @return
     *     possible object is
     *     {@link FltOrderFlightInfoListType }
     *     
     */
    public FltOrderFlightInfoListType getFlightInfoList() {
        return flightInfoList;
    }

    /**
     * Sets the value of the flightInfoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltOrderFlightInfoListType }
     *     
     */
    public void setFlightInfoList(FltOrderFlightInfoListType value) {
        this.flightInfoList = value;
    }

    /**
     * Gets the value of the passengerList property.
     * 
     * @return
     *     possible object is
     *     {@link FltOrderPassengerListType }
     *     
     */
    public FltOrderPassengerListType getPassengerList() {
        return passengerList;
    }

    /**
     * Sets the value of the passengerList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltOrderPassengerListType }
     *     
     */
    public void setPassengerList(FltOrderPassengerListType value) {
        this.passengerList = value;
    }

    /**
     * Gets the value of the contactInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FltOrderContactInfoType }
     *     
     */
    public FltOrderContactInfoType getContactInfo() {
        return contactInfo;
    }

    /**
     * Sets the value of the contactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltOrderContactInfoType }
     *     
     */
    public void setContactInfo(FltOrderContactInfoType value) {
        this.contactInfo = value;
    }

    /**
     * Gets the value of the deliverInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FltOrderDeliverInfoType }
     *     
     */
    public FltOrderDeliverInfoType getDeliverInfo() {
        return deliverInfo;
    }

    /**
     * Sets the value of the deliverInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltOrderDeliverInfoType }
     *     
     */
    public void setDeliverInfo(FltOrderDeliverInfoType value) {
        this.deliverInfo = value;
    }

    /**
     * Gets the value of the payInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FltOrderPayInfoType }
     *     
     */
    public FltOrderPayInfoType getPayInfo() {
        return payInfo;
    }

    /**
     * Sets the value of the payInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltOrderPayInfoType }
     *     
     */
    public void setPayInfo(FltOrderPayInfoType value) {
        this.payInfo = value;
    }

}
