//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.07 at 04:57:03 PM CST 
//


package com.data.data.hmly.service.ctripflight.request.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{}HeaderType"/>
 *         &lt;element name="GetAirlineInfosRequest" type="{}GetAirlineInfosRequestType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestType", propOrder = {
    "header",
    "getAirlineInfosRequest"
})
@XmlRootElement(name="Request")
public class GetAirlineInfosRequest {

    @XmlElement(name = "Header", required = true)
    protected GetAirlineInfosHeaderType header;
    @XmlElement(name = "GetAirlineInfosRequest", required = true)
    protected GetAirlineInfosRequestType getAirlineInfosRequest;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link GetAirlineInfosHeaderType }
     *     
     */
    public GetAirlineInfosHeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetAirlineInfosHeaderType }
     *     
     */
    public void setHeader(GetAirlineInfosHeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the getAirlineInfosRequest property.
     * 
     * @return
     *     possible object is
     *     {@link GetAirlineInfosRequestType }
     *     
     */
    public GetAirlineInfosRequestType getGetAirlineInfosRequest() {
        return getAirlineInfosRequest;
    }

    /**
     * Sets the value of the getAirlineInfosRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetAirlineInfosRequestType }
     *     
     */
    public void setGetAirlineInfosRequest(GetAirlineInfosRequestType value) {
        this.getAirlineInfosRequest = value;
    }

	

}
