//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 10:51:42 PM CST 
//


package com.data.data.hmly.service.ctripflight.request.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TravelerRequestListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TravelerRequestListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TravelerRequest" type="{}TravelerRequestType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TravelerRequestListType", propOrder = {
    "travelerRequest"
})
public class IntlFlightTravelerRequestListType {

    @XmlElement(name = "TravelerRequest", required = true)
    protected IntlFlightTravelerRequestType travelerRequest;

    /**
     * Gets the value of the travelerRequest property.
     * 
     * @return
     *     possible object is
     *     {@link TravelerRequestType }
     *     
     */
    public IntlFlightTravelerRequestType getTravelerRequest() {
        return travelerRequest;
    }

    /**
     * Sets the value of the travelerRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link TravelerRequestType }
     *     
     */
    public void setTravelerRequest(IntlFlightTravelerRequestType value) {
        this.travelerRequest = value;
    }

}
