//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 10:51:42 PM CST 
//


package com.data.data.hmly.service.ctripflight.request.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RouteSearchControlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteSearchControlType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RouteSearchMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RouteSearchToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrigDestSeqID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteSearchControlType", propOrder = {
    "routeSearchMode",
    "routeSearchToken",
    "origDestSeqID"
})
public class IntlFlightRouteSearchControlType {

    @XmlElement(name = "RouteSearchMode", required = true)
    protected String routeSearchMode;
    @XmlElement(name = "RouteSearchToken", required = true)
    protected String routeSearchToken;
    @XmlElement(name = "OrigDestSeqID", required = true)
    protected String origDestSeqID;

    /**
     * Gets the value of the routeSearchMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteSearchMode() {
        return routeSearchMode;
    }

    /**
     * Sets the value of the routeSearchMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteSearchMode(String value) {
        this.routeSearchMode = value;
    }

    /**
     * Gets the value of the routeSearchToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteSearchToken() {
        return routeSearchToken;
    }

    /**
     * Sets the value of the routeSearchToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteSearchToken(String value) {
        this.routeSearchToken = value;
    }

    /**
     * Gets the value of the origDestSeqID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigDestSeqID() {
        return origDestSeqID;
    }

    /**
     * Sets the value of the origDestSeqID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigDestSeqID(String value) {
        this.origDestSeqID = value;
    }

}
