//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 10:51:42 PM CST 
//


package com.data.data.hmly.service.ctripflight.request.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{}HeaderType"/>
 *         &lt;element name="IntlFlightSearchRequest" type="{}IntlFlightSearchRequestType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestType", propOrder = {
    "header",
    "intlFlightSearchRequest"
})
public class IntlFlightRequestType {

    @XmlElement(name = "Header", required = true)
    protected IntlFlightHeaderType header;
    @XmlElement(name = "IntlFlightSearchRequest", required = true)
    protected IntlFlightSearchRequestType intlFlightSearchRequest;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link FltOrderHeaderType }
     *     
     */
    public IntlFlightHeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltOrderHeaderType }
     *     
     */
    public void setHeader(IntlFlightHeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the intlFlightSearchRequest property.
     * 
     * @return
     *     possible object is
     *     {@link IntlFlightSearchRequestType }
     *     
     */
    public IntlFlightSearchRequestType getIntlFlightSearchRequest() {
        return intlFlightSearchRequest;
    }

    /**
     * Sets the value of the intlFlightSearchRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntlFlightSearchRequestType }
     *     
     */
    public void setIntlFlightSearchRequest(IntlFlightSearchRequestType value) {
        this.intlFlightSearchRequest = value;
    }

}
