//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.07 at 06:06:50 PM CST 
//


package com.data.data.hmly.service.ctripflight.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(name = "ctrip_flt_craft_info")
public class CraftInfo extends com.framework.hibernate.util.Entity{
	private static final long serialVersionUID = -2996522995238348090L;
	@Id
	@Column(name = "id", length = 11)
	private Integer id;
	
    @Column(name = "craftType")
    private String craftType;
    @Column(name = "widthLevel")
    private String widthLevel;
    @Column(name = "minSeats")
    private String minSeats;
    @Column(name = "maxSeats")
    private String maxSeats;
    @Column(name = "note")
    private String note;
    @Column(name = "craftTypeName")
    private String craftTypeName;
    @Column(name = "craftKind")
    private String craftKind;
    
    
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getCraftType() {
		return craftType;
	}
	public void setCraftType(String craftType) {
		this.craftType = craftType;
	}
	public String getWidthLevel() {
		return widthLevel;
	}
	public void setWidthLevel(String widthLevel) {
		this.widthLevel = widthLevel;
	}
	public String getMinSeats() {
		return minSeats;
	}
	public void setMinSeats(String minSeats) {
		this.minSeats = minSeats;
	}
	public String getMaxSeats() {
		return maxSeats;
	}
	public void setMaxSeats(String maxSeats) {
		this.maxSeats = maxSeats;
	}
	public String getNote() {
		return note;
	}
	public void setNote(String note) {
		this.note = note;
	}
	public String getCraftTypeName() {
		return craftTypeName;
	}
	public void setCraftTypeName(String craftTypeName) {
		this.craftTypeName = craftTypeName;
	}
	public String getCraftKind() {
		return craftKind;
	}
	public void setCraftKind(String craftKind) {
		this.craftKind = craftKind;
	}


}
