//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 03:36:59 PM CST 
//


package com.data.data.hmly.service.ctripflight.entity;

import com.data.data.hmly.service.ctripflight.entity.enums.InventoryType;
import com.data.data.hmly.service.ctripflight.entity.enums.PriceType;
import com.data.data.hmly.service.ctripflight.entity.enums.ProductType;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Entity
@Table(name = "ctrip_flight_info")
public class CtripFlightInfo extends com.framework.hibernate.util.Entity {
	private static final long serialVersionUID = -2996522995238348090L;
	@Id
	@Column(name = "id", length = 11)
    private Integer id;
    @Column(name = "departCityCode")	
    private String departCityCode;		//出发机场三字码
    @Column(name = "arriveCityCode")
    private String arriveCityCode;		//到达机场三字码
    @Column(name = "takeOffTime")
    private Date takeOffTime;			//起飞时间
    @Column(name = "arriveTime")
    private Date arriveTime;			//抵达时间
    @Column(name = "flight")
    private String flight;			//航班号
    @Column(name = "craftType")
    private String craftType;			//机型
    @Column(name = "airlineCode")
    private String airlineCode;			//航空公司代码
    @Column(name = "class")
    private String clazz;			//舱位等级：对应航班查询结果的FlightClass 字段
    @Column(name = "subClass")
    private String subClass;			//子舱位
    @Column(name = "displaySubclass")
    private String displaySubclass;			//显示用舱位
    @Column(name = "rate")
    private String rate;			//航班扣率
    @Column(name = "price")
    private String price;			//航班票价
    @Column(name = "standardPrice")
    private String standardPrice;			//标准价
    @Column(name = "childStandardPrice")
    private String childStandardPrice;			//抵达时间儿童标准价
    @Column(name = "babyStandardPrice")
    private String babyStandardPrice;			//婴儿标准价
    @Column(name = "mealType")
    private String mealType;			//餐食类型
    @Column(name = "adultTax")
    private String adultTax;			//成人税
    @Column(name = "babyTax")
    private String babyTax;			//婴儿税
    @Column(name = "childTax")
    private String childTax;			//儿童税
    @Column(name = "adultOilFee")
    private Integer adultOilFee;			//成人燃油费用
    @Column(name = "babyOilFee")
    private Integer babyOilFee;			//婴儿燃油费用
    @Column(name = "childOilFee")
    private Integer childOilFee;			//儿童燃油费用
    @Column(name = "dPortCode")
    private String dPortCode;			//出发机场代码
    @Column(name = "aPortCode")
    private String aPortCode;			//抵达机场代码
    @Column(name = "dPortBuildingID")
    private String dPortBuildingID;			//出发机场航站楼ID
    @Column(name = "aPortBuildingID")
    private String aPortBuildingID;			//到达机场航站楼ID
    @Column(name = "aPortBuildingCheckInTime")
    private Integer aPortBuildingCheckInTime;			//出发机场航站楼检票时间
    @Column(name = "dPortBuildingCheckInTime")
    private Integer dPortBuildingCheckInTime;			//出发机场航站楼检票时间
    @Column(name = "stopTimes")
    private Integer stopTimes;			//经停次数
    @Column(name = "nonrer")
    private String nonrer;			//更标示
    @Column(name = "nonend")
    private String nonend;			//转签标示
    @Column(name = "nonref")
    private String nonref;			//退票标示
    @Column(name = "rernote" ,length=2000)
    private String rernote;			//更改说明 （中文 或 英文）中文、英文 的显示取决于请求Header 节Culture 值
    @Column(name = "endnote",length=2000)
    private String endnote;			//转签说明 （中文 或 英文）中文、英文 的显示取决于请求Header 节Culture 值
    @Column(name = "refnote",length=2000)
    private String refnote;			//退票说明 （中文 或 英文）中文、英文 的显示取决于请求Header 节Culture 值
    @Column(name = "remarks",length=2000)
    private String remarks;			//备注 （中文或英文）中文、英文 的显示取决于请求Header 节Culture 值
    @Column(name = "ticketType")
    private String ticketType;			//票种,中文、英文 的显示取决于请求Header 节Culture 值
    @Column(name = "beforeFlyDate")
    private Integer beforeFlyDate;			//提前预定天数
    @Column(name = "quantity")
    private String quantity;			//剩余票量Int32 中文、英文 的显示取决于请求Header 节Culture 值
    @Column(name = "priceType")
    private PriceType priceType;			//价格类型 NormalPrice ：普通,SingleTripPrice：提前预售特价,CZSpecialPrice：南航特价
    @Column(name = "productType")
    private ProductType productType;			//机票产品类型:Normal,YOUNGMAN,OLDMAN
    @Column(name = "productSource")
    private String productSource;			//机票产品来源:1携程机票频道,2共享平台,3两者共有,4直连产品
    @Column(name = "inventoryType")
    private InventoryType inventoryType;			//库存类型:FIX：定额   FAV：见舱
    @Column(name = "routeIndex")
    private Integer routeIndex;			//航程索引
    @Column(name = "needApplyString")
    private String needApplyString;			//是否K位
    @Column(name = "recommend")
    private String recommend;			//推荐等级
    @Column(name = "refundFeeFormulaID")
    private String refundFeeFormulaID;			//退票费公式ID
    @Column(name = "canUpGrade")
    private boolean canUpGrade;			//是否可升舱
    @Column(name = "canSeparateSale")
    private boolean canSeparateSale;			//是否可单独销售
    @Column(name = "canNoDefer")
    private boolean canNoDefer;			//是否随订随售
    @Column(name = "isFlyMan")
    private boolean isFlyMan;			//是否飞人航班
    @Column(name = "onlyOwnCity")
    private boolean onlyOwnCity;			//是否政策限本地
    @Column(name = "isLowestPrice")
    private boolean isLowestPrice;			//是否最低价
    @Column(name = "isLowestCZSpecialPrice")
    private boolean isLowestCZSpecialPrice;			//是否南航最低价
    @Column(name = "punctualityRate")
    private String punctualityRate;			//参考准点率
    @Column(name = "policyID")
    private String policyID;			//政策ID
    @Column(name = "allowCPType")
    private String allowCPType;			//原政策可出票种:对应航班查询结果中的DeliverTicketType 字段
    @Column(name = "outOfPostTime")
    private boolean outOfPostTime;			//是否超出邮寄时间
    @Column(name = "outOfSendGetTime")
    private boolean outOfSendGetTime;			//是否在送票取票时间之外
    @Column(name = "outOfAirlineCounterTime")
    private boolean outOfAirlineCounterTime;			//是否在柜台取票时间之外
    @Column(name = "oanPost")
    private boolean canPost;			//是否可邮寄
    @Column(name = "canAirlineCounter")
    private boolean canAirlineCounter;			//是否可航空公司柜台取消
    @Column(name = "canSendGet")
    private boolean canSendGet;			//是否可市内送票取票
    @Column(name = "isRebate")
    private boolean isRebate;			//是否返现
    @Column(name = "rebateAmount")
    private String rebateAmount;			//返现金额
    @Column(name = "rebateCPCity")
    private String rebateCPCity;			//是否飞人航班
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getDepartCityCode() {
		return departCityCode;
	}
	public void setDepartCityCode(String departCityCode) {
		this.departCityCode = departCityCode;
	}
	public String getArriveCityCode() {
		return arriveCityCode;
	}
	public void setArriveCityCode(String arriveCityCode) {
		this.arriveCityCode = arriveCityCode;
	}
	public Date getTakeOffTime() {
		return takeOffTime;
	}
	public void setTakeOffTime(Date takeOffTime) {
		this.takeOffTime = takeOffTime;
	}
	public Date getArriveTime() {
		return arriveTime;
	}
	public void setArriveTime(Date arriveTime) {
		this.arriveTime = arriveTime;
	}
	public String getFlight() {
		return flight;
	}
	public void setFlight(String flight) {
		this.flight = flight;
	}
	public String getCraftType() {
		return craftType;
	}
	public void setCraftType(String craftType) {
		this.craftType = craftType;
	}
	public String getAirlineCode() {
		return airlineCode;
	}
	public void setAirlineCode(String airlineCode) {
		this.airlineCode = airlineCode;
	}
	public String getClazz() {
		return clazz;
	}
	public void setClazz(String clazz) {
		this.clazz = clazz;
	}
	public String getSubClass() {
		return subClass;
	}
	public void setSubClass(String subClass) {
		this.subClass = subClass;
	}
	public String getDisplaySubclass() {
		return displaySubclass;
	}
	public void setDisplaySubclass(String displaySubclass) {
		this.displaySubclass = displaySubclass;
	}
	public String getRate() {
		return rate;
	}
	public void setRate(String rate) {
		this.rate = rate;
	}
	public String getPrice() {
		return price;
	}
	public void setPrice(String price) {
		this.price = price;
	}
	public String getStandardPrice() {
		return standardPrice;
	}
	public void setStandardPrice(String standardPrice) {
		this.standardPrice = standardPrice;
	}
	public String getChildStandardPrice() {
		return childStandardPrice;
	}
	public void setChildStandardPrice(String childStandardPrice) {
		this.childStandardPrice = childStandardPrice;
	}
	public String getBabyStandardPrice() {
		return babyStandardPrice;
	}
	public void setBabyStandardPrice(String babyStandardPrice) {
		this.babyStandardPrice = babyStandardPrice;
	}
	public String getMealType() {
		return mealType;
	}
	public void setMealType(String mealType) {
		this.mealType = mealType;
	}
	public String getAdultTax() {
		return adultTax;
	}
	public void setAdultTax(String adultTax) {
		this.adultTax = adultTax;
	}
	public String getBabyTax() {
		return babyTax;
	}
	public void setBabyTax(String babyTax) {
		this.babyTax = babyTax;
	}
	public String getChildTax() {
		return childTax;
	}
	public void setChildTax(String childTax) {
		this.childTax = childTax;
	}
	public Integer getAdultOilFee() {
		return adultOilFee;
	}
	public void setAdultOilFee(Integer adultOilFee) {
		this.adultOilFee = adultOilFee;
	}
	public Integer getBabyOilFee() {
		return babyOilFee;
	}
	public void setBabyOilFee(Integer babyOilFee) {
		this.babyOilFee = babyOilFee;
	}
	public Integer getChildOilFee() {
		return childOilFee;
	}
	public void setChildOilFee(Integer childOilFee) {
		this.childOilFee = childOilFee;
	}
	public String getdPortCode() {
		return dPortCode;
	}
	public void setdPortCode(String dPortCode) {
		this.dPortCode = dPortCode;
	}
	public String getaPortCode() {
		return aPortCode;
	}
	public void setaPortCode(String aPortCode) {
		this.aPortCode = aPortCode;
	}
	public String getdPortBuildingID() {
		return dPortBuildingID;
	}
	public void setdPortBuildingID(String dPortBuildingID) {
		this.dPortBuildingID = dPortBuildingID;
	}
	public String getaPortBuildingID() {
		return aPortBuildingID;
	}
	public void setaPortBuildingID(String aPortBuildingID) {
		this.aPortBuildingID = aPortBuildingID;
	}
	public Integer getStopTimes() {
		return stopTimes;
	}
	public void setStopTimes(Integer stopTimes) {
		this.stopTimes = stopTimes;
	}
	public String getNonrer() {
		return nonrer;
	}
	public void setNonrer(String nonrer) {
		this.nonrer = nonrer;
	}
	public String getNonend() {
		return nonend;
	}
	public void setNonend(String nonend) {
		this.nonend = nonend;
	}
	public String getNonref() {
		return nonref;
	}
	public void setNonref(String nonref) {
		this.nonref = nonref;
	}
	public String getRernote() {
		return rernote;
	}
	public void setRernote(String rernote) {
		this.rernote = rernote;
	}
	public String getEndnote() {
		return endnote;
	}
	public void setEndnote(String endnote) {
		this.endnote = endnote;
	}
	public String getRefnote() {
		return refnote;
	}
	public void setRefnote(String refnote) {
		this.refnote = refnote;
	}
	public String getRemarks() {
		return remarks;
	}
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	public String getTicketType() {
		return ticketType;
	}
	public void setTicketType(String ticketType) {
		this.ticketType = ticketType;
	}
	public Integer getBeforeFlyDate() {
		return beforeFlyDate;
	}
	public void setBeforeFlyDate(Integer beforeFlyDate) {
		this.beforeFlyDate = beforeFlyDate;
	}
	public String getQuantity() {
		return quantity;
	}
	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}
	public PriceType getPriceType() {
		return priceType;
	}
	public void setPriceType(PriceType priceType) {
		this.priceType = priceType;
	}
	public ProductType getProductType() {
		return productType;
	}
	public void setProductType(ProductType productType) {
		this.productType = productType;
	}
	public String getProductSource() {
		return productSource;
	}
	public void setProductSource(String productSource) {
		this.productSource = productSource;
	}
	public InventoryType getInventoryType() {
		return inventoryType;
	}
	public void setInventoryType(InventoryType inventoryType) {
		this.inventoryType = inventoryType;
	}
	public Integer getRouteIndex() {
		return routeIndex;
	}
	public void setRouteIndex(Integer routeIndex) {
		this.routeIndex = routeIndex;
	}
	public String getNeedApplyString() {
		return needApplyString;
	}
	public void setNeedApplyString(String needApplyString) {
		this.needApplyString = needApplyString;
	}
	public String getRecommend() {
		return recommend;
	}
	public void setRecommend(String recommend) {
		this.recommend = recommend;
	}
	public String getRefundFeeFormulaID() {
		return refundFeeFormulaID;
	}
	public void setRefundFeeFormulaID(String refundFeeFormulaID) {
		this.refundFeeFormulaID = refundFeeFormulaID;
	}
	public boolean isCanUpGrade() {
		return canUpGrade;
	}
	public void setCanUpGrade(boolean canUpGrade) {
		this.canUpGrade = canUpGrade;
	}
	public boolean isCanSeparateSale() {
		return canSeparateSale;
	}
	public void setCanSeparateSale(boolean canSeparateSale) {
		this.canSeparateSale = canSeparateSale;
	}
	public boolean isCanNoDefer() {
		return canNoDefer;
	}
	public void setCanNoDefer(boolean canNoDefer) {
		this.canNoDefer = canNoDefer;
	}
	public boolean isFlyMan() {
		return isFlyMan;
	}
	public void setFlyMan(boolean isFlyMan) {
		this.isFlyMan = isFlyMan;
	}
	public boolean isOnlyOwnCity() {
		return onlyOwnCity;
	}
	public void setOnlyOwnCity(boolean onlyOwnCity) {
		this.onlyOwnCity = onlyOwnCity;
	}
	public boolean isLowestPrice() {
		return isLowestPrice;
	}
	public void setLowestPrice(boolean isLowestPrice) {
		this.isLowestPrice = isLowestPrice;
	}
	public boolean isLowestCZSpecialPrice() {
		return isLowestCZSpecialPrice;
	}
	public void setLowestCZSpecialPrice(boolean isLowestCZSpecialPrice) {
		this.isLowestCZSpecialPrice = isLowestCZSpecialPrice;
	}
	public String getPunctualityRate() {
		return punctualityRate;
	}
	public void setPunctualityRate(String punctualityRate) {
		this.punctualityRate = punctualityRate;
	}
	public String getPolicyID() {
		return policyID;
	}
	public void setPolicyID(String policyID) {
		this.policyID = policyID;
	}
	public String getAllowCPType() {
		return allowCPType;
	}
	public void setAllowCPType(String allowCPType) {
		this.allowCPType = allowCPType;
	}
	public boolean isOutOfPostTime() {
		return outOfPostTime;
	}
	public void setOutOfPostTime(boolean outOfPostTime) {
		this.outOfPostTime = outOfPostTime;
	}
	public boolean isOutOfSendGetTime() {
		return outOfSendGetTime;
	}
	public void setOutOfSendGetTime(boolean outOfSendGetTime) {
		this.outOfSendGetTime = outOfSendGetTime;
	}
	public boolean isOutOfAirlineCounterTime() {
		return outOfAirlineCounterTime;
	}
	public void setOutOfAirlineCounterTime(boolean outOfAirlineCounterTime) {
		this.outOfAirlineCounterTime = outOfAirlineCounterTime;
	}
	public boolean isCanPost() {
		return canPost;
	}
	public void setCanPost(boolean canPost) {
		this.canPost = canPost;
	}
	public boolean isCanAirlineCounter() {
		return canAirlineCounter;
	}
	public void setCanAirlineCounter(boolean canAirlineCounter) {
		this.canAirlineCounter = canAirlineCounter;
	}
	public boolean isCanSendGet() {
		return canSendGet;
	}
	public void setCanSendGet(boolean canSendGet) {
		this.canSendGet = canSendGet;
	}
	public boolean isRebate() {
		return isRebate;
	}
	public void setRebate(boolean isRebate) {
		this.isRebate = isRebate;
	}
	public String getRebateAmount() {
		return rebateAmount;
	}
	public void setRebateAmount(String rebateAmount) {
		this.rebateAmount = rebateAmount;
	}
	public String getRebateCPCity() {
		return rebateCPCity;
	}
	public void setRebateCPCity(String rebateCPCity) {
		this.rebateCPCity = rebateCPCity;
	}
	public Integer getaPortBuildingCheckInTime() {
		return aPortBuildingCheckInTime;
	}
	public void setaPortBuildingCheckInTime(Integer aPortBuildingCheckInTime) {
		this.aPortBuildingCheckInTime = aPortBuildingCheckInTime;
	}
	public Integer getdPortBuildingCheckInTime() {
		return dPortBuildingCheckInTime;
	}
	public void setdPortBuildingCheckInTime(Integer dPortBuildingCheckInTime) {
		this.dPortBuildingCheckInTime = dPortBuildingCheckInTime;
	}
   

}
