//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 10:55:20 AM CST 
//


package com.data.data.hmly.service.ctripflight.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "ctrip_flt_route_info")
public class FlightRoute {
	private static final long serialVersionUID = -2996522995238348090L;
	@Id
	@Column(name = "id", length = 11)
	private Integer id;
    @Column(name = "departCity")
    private String departCity;
    @Column(name = "arriveCity")
    private String arriveCity;
    @Column(name = "departDate")
    private String departDate;
    @Column(name = "airlineDibitCode")
    private String airlineDibitCode;
    @Column(name = "departPort")
    private String departPort;
    @Column(name = "arrivePort")
    private String arrivePort;
    @Column(name = "earliestDepartTime")
    private String earliestDepartTime;
    @Column(name = "latestDepartTime")
    private String latestDepartTime;
    
    
    
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getDepartCity() {
		return departCity;
	}
	public void setDepartCity(String departCity) {
		this.departCity = departCity;
	}
	public String getArriveCity() {
		return arriveCity;
	}
	public void setArriveCity(String arriveCity) {
		this.arriveCity = arriveCity;
	}
	public String getDepartDate() {
		return departDate;
	}
	public void setDepartDate(String departDate) {
		this.departDate = departDate;
	}
	public String getAirlineDibitCode() {
		return airlineDibitCode;
	}
	public void setAirlineDibitCode(String airlineDibitCode) {
		this.airlineDibitCode = airlineDibitCode;
	}
	public String getDepartPort() {
		return departPort;
	}
	public void setDepartPort(String departPort) {
		this.departPort = departPort;
	}
	public String getArrivePort() {
		return arrivePort;
	}
	public void setArrivePort(String arrivePort) {
		this.arrivePort = arrivePort;
	}
	public String getEarliestDepartTime() {
		return earliestDepartTime;
	}
	public void setEarliestDepartTime(String earliestDepartTime) {
		this.earliestDepartTime = earliestDepartTime;
	}
	public String getLatestDepartTime() {
		return latestDepartTime;
	}
	public void setLatestDepartTime(String latestDepartTime) {
		this.latestDepartTime = latestDepartTime;
	}

}
