//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.07 at 11:16:00 AM CST 
//


package com.data.data.hmly.service.ctripflight.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "ctrip_flt_city_info")
public class FltCityInfo extends com.framework.hibernate.util.Entity {
	

	
	private static final long serialVersionUID = -2996522995238348090L;
	@Id
	@Column(name = "id", length = 11)
	private Integer id;
    @Column(name = "cityCode")
    private String cityCode;
    @Column(name = "cityId")
    private Integer cityId;
    @Column(name = "cityName")
    private String cityName;
    @Column(name = "provinceId")
    private Integer provinceId;
    @Column(name = "countryId")
    private Integer countryId;
    @Column(name = "countryName")
    private String countryName;
    @Column(name = "isDomesticCity")
    private boolean isDomesticCity;
    
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getCityCode() {
		return cityCode;
	}
	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}
	public Integer getCityId() {
		return cityId;
	}
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}
	public String getCityName() {
		return cityName;
	}
	public void setCityName(String cityName) {
		this.cityName = cityName;
	}
	public Integer getProvinceId() {
		return provinceId;
	}
	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}
	public Integer getCountryId() {
		return countryId;
	}
	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}
	public String getCountryName() {
		return countryName;
	}
	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}
	public boolean isDomesticCity() {
		return isDomesticCity;
	}
	public void setDomesticCity(boolean isDomesticCity) {
		this.isDomesticCity = isDomesticCity;
	}


}
