//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.05 at 01:48:07 PM CST 
//


package com.data.data.hmly.service.ctripflight.entity;

import com.data.data.hmly.service.ctripflight.entity.enums.OrderType;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Entity
@Table(name = "ctrip_flt_order_info")
public class FltOrderInfo extends com.framework.hibernate.util.Entity{
	
	private static final long serialVersionUID = -2996522995238348090L;
	@Id
	@Column(name = "id", length = 11)
	private Integer id;
	
	@Column(name = "userid", length = 20)
	private String userId;
	
	@Column(name = "orderType")
	@Enumerated(EnumType.STRING)
	private OrderType orderType;
	
	@Column(name = "amount")
	private Integer amount;
	
	@Column(name = "contactid", length = 20)
	private Integer contactId;
	
	@Column(name = "deliverid", length = 20)
	private Integer deliverId;
	
	@Column(name = "creditCardid", length = 20)
	private Integer payInfoId;
	
	@Column(name = "createBy")
	private Long createBy;
	@Column(name = "createTime")
	private Date createTime;
	@Column(name = "updateTime")
	private Date updateTime;
	
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getUserId() {
		return userId;
	}
	public void setUserId(String userId) {
		this.userId = userId;
	}
	public OrderType getOrderType() {
		return orderType;
	}
	public void setOrderType(OrderType orderType) {
		this.orderType = orderType;
	}
	public Integer getAmount() {
		return amount;
	}
	public void setAmount(Integer amount) {
		this.amount = amount;
	}
	public Long getCreateBy() {
		return createBy;
	}
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public Date getUpdateTime() {
		return updateTime;
	}
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	public Integer getContactId() {
		return contactId;
	}
	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}
	public Integer getDeliverId() {
		return deliverId;
	}
	public void setDeliverId(Integer deliverId) {
		this.deliverId = deliverId;
	}
	public Integer getPayInfoId() {
		return payInfoId;
	}
	public void setPayInfoId(Integer payInfoId) {
		this.payInfoId = payInfoId;
	}
}
