//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.05 at 01:48:07 PM CST 
//


package com.data.data.hmly.service.ctripflight.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(name = "ctrip_flt_order_deliver_info")
public class FltOrderDeliverInfo extends com.framework.hibernate.util.Entity {

	
	private static final long serialVersionUID = -2996522995238348090L;
	@Id
	@Column(name = "id", length = 11)
	private Integer id;
	
    @Column(name = "deliveryType")
    private String deliveryType;
    @Column(name = "sendTicketCityID")
    private String sendTicketCityID;
    @Column(name = "orderRemark")
    private String orderRemark;
    
    @Column(name = "pjsid")
    private Integer pjsid;
    
    
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getDeliveryType() {
		return deliveryType;
	}
	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}
	public String getSendTicketCityID() {
		return sendTicketCityID;
	}
	public void setSendTicketCityID(String sendTicketCityID) {
		this.sendTicketCityID = sendTicketCityID;
	}
	public String getOrderRemark() {
		return orderRemark;
	}
	public void setOrderRemark(String orderRemark) {
		this.orderRemark = orderRemark;
	}
	public Integer getPjsid() {
		return pjsid;
	}
	public void setPjsid(Integer pjsid) {
		this.pjsid = pjsid;
	}


}
